package net.idtoki.adimde.helper;

import net.idtoki.adimde.model.Centros;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Oct 02 10:34:00 CEST 2006]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class CentrosHelper
    extends net.idtoki.adimde.helper.BaseCentrosHelper
{
		    			public CentrosHelper()
    {
        super();
    }
    public CentrosHelper(Centros obj)
    {
        super(obj);
    }
}


