package net.idtoki.adimde.app.event;

import net.zylk.web.listener.BaseServletContextListener;
import java.util.logging.Logger;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Oct 02 16:27:35 CEST 2006]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class OnStartUp extends BaseServletContextListener
{
 private static final Logger logger = Logger.getLogger("net.idtoki.adimde.app.event.OnStartUp");

  public String getConfigFilePath() {
  return "net/idtoki/adimde/app/config/app-config";
 }
}


