package net.idtoki.adimde.group;

import net.idtoki.adimde.model.CentrosPeer;
import net.idtoki.adimde.model.Centros;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Oct 02 10:34:00 CEST 2006]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class CentrosGroupBean
    extends net.idtoki.adimde.group.BaseCentrosGroupBean
{
  public CentrosGroupBean(){
        this.dbField = CentrosPeer.IDCENTRO;
                      
//podemos fijar el numero de elementos por pagina recogiendo el entero de un archivo de configuracion
//this.setNumeroElementosPorPagina(int);
//si no se utiliza this.setNumeroElementosPorPagina(); el numero por defecto es 10

  }
}


