
package net.idtoki.adimde.model;


import java.util.logging.Logger;

import net.zylk.tools.format.FormatUtils;

import org.apache.torque.TorqueException;
import org.apache.torque.om.Persistent;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Oct 26 17:10:22 CEST 2006]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class Estadosproduccion
    extends net.idtoki.adimde.model.BaseEstadosproduccion
    implements Persistent
{

private static final Logger logger = Logger.getLogger("net.idtoki.adimde.model.Estadosproduccion");


		
	public String getIdestadoproduccionEstadosproduccionParsed()
	{
		return FormatUtils.genericParsedStr(this.getIdestadoproduccion() + "");
	}					

		
	public String getDescripcionEstadosproduccionParsed()
	{
		return FormatUtils.genericParsedStr(this.getDescripcion());		
	}					


	public String getPathEstadosproduccionParsed(String strQueryString) throws TorqueException
	{	
	  String a = "";
	  a = a + this.getDescripcionEstadosproduccionParsed();  
	  return a;
	}

	public String getULContentEstadosproduccionParsed() throws TorqueException
	{
		return FormatUtils.genericParsedStr(this.getIdestadoproduccion() + "-" + this.getDescripcionEstadosproduccionParsed());	
	}	

	public String getHijosProduccionesEstadosproduccion()
	{
		return "<a href='#' class='hijos' id='getHijosProduccionesEstadosproduccion" + this.getIdestadoproduccion() + "' title='Producciones'>&#160;&#160;&#160;&#160;</a>";
	}
	
	public String getDeleteEstadosproduccion()
	{
		return "<a href='#' class='eliminar' id='getDeleteEstadosproduccion" + this.getIdestadoproduccion() + "' title='Borrar'>&#160;&#160;&#160;&#160;</a>";
	}	
	public String getEditEstadosproduccion()
	{
		return "<a href='#' class='edicion' id='getEditEstadosproduccion" + this.getIdestadoproduccion() + "' title='Editar'>&#160;&#160;&#160;&#160;</a>";
	}

}
