
package net.idtoki.adimde.model;


import java.util.logging.Logger;

import net.zylk.tools.format.FormatUtils;

import org.apache.torque.TorqueException;
import org.apache.torque.om.Persistent;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Oct 02 10:34:00 CEST 2006]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class Perfilturno
    extends net.idtoki.adimde.model.BasePerfilturno
    implements Persistent
{

private static final Logger logger = Logger.getLogger("net.idtoki.adimde.model.Perfilturno");


		
	public String getIdtpPerfilturnoParsed()
	{
		return FormatUtils.genericParsedStr(this.getIdtp() + "");
	}					

		
	public String getIdperfilPerfilturnoParsed()
	{
		String strFK=null;
		try
		{
			strFK=this.getPerfiles().getULContentPerfilesParsed();
		}
		catch (TorqueException te) {
			logger.severe("No se ha podido localizar Perfiles. getIdperfilPerfilturnoParsed()" );
			te.printStackTrace();
		}
		return FormatUtils.genericParsedStr(strFK);		
	}					

		
	public String getIdturnoPerfilturnoParsed()
	{
		String strFK=null;
		try
		{
			strFK=this.getTurnos().getULContentTurnosParsed();
		}
		catch (TorqueException te) {
			logger.severe("No se ha podido localizar Turnos. getIdturnoPerfilturnoParsed()" );
			te.printStackTrace();
		}
		return FormatUtils.genericParsedStr(strFK);		
	}					

		
	public String getValorcostePerfilturnoParsed()
	{
		return FormatUtils.genericParsedStr(this.getValorcoste() + "");	 
	}					


	public String getPathPerfilturnoParsed(String strQueryString) throws TorqueException
	{	
	  String a = "";
	  if (strQueryString.indexOf("perfiles") != -1)	  
	  	a = a + this.getPerfiles().getPathPerfilesParsed(strQueryString) + "/";
	  if (strQueryString.indexOf("turnos") != -1)	  
	  	a = a + this.getTurnos().getPathTurnosParsed(strQueryString) + "/";
	  a = a + this.getPerfiles().getDescripcionPerfilesParsed() + "_" + this.getTurnos().getDescripcionTurnosParsed();  
	  return a;
	}

	public String getULContentPerfilturnoParsed() throws TorqueException
	{
		return FormatUtils.genericParsedStr(this.getIdtp() + "-" + this.getPerfiles().getDescripcionPerfilesParsed() + "_" + this.getTurnos().getDescripcionTurnosParsed());	
	}	

	
	public String getDeletePerfilturno()
	{
		return "<a href='#' class='eliminar' id='getDeletePerfilturno" + this.getIdtp() + "' title='Borrar'>&#160;&#160;&#160;&#160;</a>";
	}	
	public String getEditPerfilturno()
	{
		return "<a href='#' class='edicion' id='getEditPerfilturno" + this.getIdtp() + "' title='Editar'>&#160;&#160;&#160;&#160;</a>";
	}

}
