
package net.idtoki.adimde.model;


import java.util.logging.Logger;

import net.zylk.tools.format.FormatUtils;

import org.apache.torque.TorqueException;
import org.apache.torque.om.Persistent;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Oct 02 10:34:00 CEST 2006]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class Perfiles
    extends net.idtoki.adimde.model.BasePerfiles
    implements Persistent
{

private static final Logger logger = Logger.getLogger("net.idtoki.adimde.model.Perfiles");


		
	public String getIdperfilPerfilesParsed()
	{
		return FormatUtils.genericParsedStr(this.getIdperfil() + "");
	}					

		
	public String getDescripcionPerfilesParsed()
	{
		return FormatUtils.genericParsedStr(this.getDescripcion());		
	}					


	public String getPathPerfilesParsed(String strQueryString) throws TorqueException
	{	
	  String a = "";
	  a = a + this.getDescripcionPerfilesParsed();  
	  return a;
	}

	public String getULContentPerfilesParsed() throws TorqueException
	{
		return FormatUtils.genericParsedStr(this.getIdperfil() + "-" + this.getDescripcionPerfilesParsed());	
	}	

	public String getHijosOperariosPerfiles()
	{
		return "<a href='#' class='hijos' id='getHijosOperariosPerfiles" + this.getIdperfil() + "' title='Operarios'>&#160;&#160;&#160;&#160;</a>";
	}
	public String getHijosPerfilturnoPerfiles()
	{
		return "<a href='#' class='hijos' id='getHijosPerfilturnoPerfiles" + this.getIdperfil() + "' title='Perfilturno'>&#160;&#160;&#160;&#160;</a>";
	}
	
	public String getDeletePerfiles()
	{
		return "<a href='#' class='eliminar' id='getDeletePerfiles" + this.getIdperfil() + "' title='Borrar'>&#160;&#160;&#160;&#160;</a>";
	}	
	public String getEditPerfiles()
	{
		return "<a href='#' class='edicion' id='getEditPerfiles" + this.getIdperfil() + "' title='Editar'>&#160;&#160;&#160;&#160;</a>";
	}

}
