
package net.idtoki.adimde.model;


import java.util.logging.Logger;

import net.zylk.tools.format.FormatUtils;

import org.apache.torque.TorqueException;
import org.apache.torque.om.Persistent;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Oct 02 10:34:00 CEST 2006]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class Tipotrabajos
    extends net.idtoki.adimde.model.BaseTipotrabajos
    implements Persistent
{

private static final Logger logger = Logger.getLogger("net.idtoki.adimde.model.Tipotrabajos");


		
	public String getIdtipotrabajoTipotrabajosParsed()
	{
		return FormatUtils.genericParsedStr(this.getIdtipotrabajo() + "");
	}					

		
	public String getNombreTipotrabajosParsed()
	{
		return FormatUtils.genericParsedStr(this.getNombre());		
	}					

		
	public String getDescripcionTipotrabajosParsed()
	{
		return FormatUtils.genericParsedStr(this.getDescripcion());		
	}					

		
	public String getCosteTipotrabajosParsed()
	{
		return FormatUtils.genericParsedStr(this.getCoste() + "");	 
	}					


	public String getPathTipotrabajosParsed(String strQueryString) throws TorqueException
	{	
	  String a = "";
	  a = a + this.getNombreTipotrabajosParsed();  
	  return a;
	}

	public String getULContentTipotrabajosParsed() throws TorqueException
	{
		return FormatUtils.genericParsedStr(this.getIdtipotrabajo() + "-" + this.getNombreTipotrabajosParsed());	
	}	

	public String getHijosProduccionesTipotrabajos()
	{
		return "<a href='#' class='hijos' id='getHijosProduccionesTipotrabajos" + this.getIdtipotrabajo() + "' title='Producciones'>&#160;&#160;&#160;&#160;</a>";
	}
	
	public String getDeleteTipotrabajos()
	{
		return "<a href='#' class='eliminar' id='getDeleteTipotrabajos" + this.getIdtipotrabajo() + "' title='Borrar'>&#160;&#160;&#160;&#160;</a>";
	}	
	public String getEditTipotrabajos()
	{
		return "<a href='#' class='edicion' id='getEditTipotrabajos" + this.getIdtipotrabajo() + "' title='Editar'>&#160;&#160;&#160;&#160;</a>";
	}

}
