
package net.idtoki.adimde.model;


import java.util.logging.Logger;

import net.zylk.tools.format.FormatUtils;

import org.apache.torque.TorqueException;
import org.apache.torque.om.Persistent;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Oct 02 10:34:00 CEST 2006]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class Turnos
    extends net.idtoki.adimde.model.BaseTurnos
    implements Persistent
{

private static final Logger logger = Logger.getLogger("net.idtoki.adimde.model.Turnos");


		
	public String getIdturnoTurnosParsed()
	{
		return FormatUtils.genericParsedStr(this.getIdturno() + "");
	}					

		
	public String getDescripcionTurnosParsed()
	{
		return FormatUtils.genericParsedStr(this.getDescripcion());		
	}					


	public String getPathTurnosParsed(String strQueryString) throws TorqueException
	{	
	  String a = "";
	  a = a + this.getDescripcionTurnosParsed();  
	  return a;
	}

	public String getULContentTurnosParsed() throws TorqueException
	{
		return FormatUtils.genericParsedStr(this.getIdturno() + "-" + this.getDescripcionTurnosParsed());	
	}	

	public String getHijosPartesTurnos()
	{
		return "<a href='#' class='hijos' id='getHijosPartesTurnos" + this.getIdturno() + "' title='Partes'>&#160;&#160;&#160;&#160;</a>";
	}
	public String getHijosPerfilturnoTurnos()
	{
		return "<a href='#' class='hijos' id='getHijosPerfilturnoTurnos" + this.getIdturno() + "' title='Perfilturno'>&#160;&#160;&#160;&#160;</a>";
	}
	
	public String getDeleteTurnos()
	{
		return "<a href='#' class='eliminar' id='getDeleteTurnos" + this.getIdturno() + "' title='Borrar'>&#160;&#160;&#160;&#160;</a>";
	}	
	public String getEditTurnos()
	{
		return "<a href='#' class='edicion' id='getEditTurnos" + this.getIdturno() + "' title='Editar'>&#160;&#160;&#160;&#160;</a>";
	}

}
