
package net.idtoki.adimde.model;


import java.util.logging.Logger;

import net.zylk.tools.format.FormatUtils;

import org.apache.torque.TorqueException;
import org.apache.torque.om.Persistent;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Oct 26 17:10:22 CEST 2006]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class Unidadesmedida
    extends net.idtoki.adimde.model.BaseUnidadesmedida
    implements Persistent
{

private static final Logger logger = Logger.getLogger("net.idtoki.adimde.model.Unidadesmedida");


		
	public String getIdunidadmedidaUnidadesmedidaParsed()
	{
		return FormatUtils.genericParsedStr(this.getIdunidadmedida() + "");
	}					

		
	public String getDescripcionUnidadesmedidaParsed()
	{
		return FormatUtils.genericParsedStr(this.getDescripcion());		
	}					


	public String getPathUnidadesmedidaParsed(String strQueryString) throws TorqueException
	{	
	  String a = "";
	  a = a + this.getDescripcionUnidadesmedidaParsed();  
	  return a;
	}

	public String getULContentUnidadesmedidaParsed() throws TorqueException
	{
		return FormatUtils.genericParsedStr(this.getIdunidadmedida() + "-" + this.getDescripcionUnidadesmedidaParsed());	
	}	

	public String getHijosMaterialesUnidadesmedida()
	{
		return "<a href='#' class='hijos' id='getHijosMaterialesUnidadesmedida" + this.getIdunidadmedida() + "' title='Materiales'>&#160;&#160;&#160;&#160;</a>";
	}
	
	public String getDeleteUnidadesmedida()
	{
		return "<a href='#' class='eliminar' id='getDeleteUnidadesmedida" + this.getIdunidadmedida() + "' title='Borrar'>&#160;&#160;&#160;&#160;</a>";
	}	
	public String getEditUnidadesmedida()
	{
		return "<a href='#' class='edicion' id='getEditUnidadesmedida" + this.getIdunidadmedida() + "' title='Editar'>&#160;&#160;&#160;&#160;</a>";
	}

}
