package net.idtoki.adimde.model;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Oct 26 17:10:22 CEST 2006]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class UnidadesmedidaPeer
    extends net.idtoki.adimde.model.BaseUnidadesmedidaPeer
{
}
