package net.idtoki.adimde.manager;

import org.apache.torque.TorqueException;
import org.apache.torque.util.Criteria;

import net.idtoki.adimde.model.EstadosproduccionPeer;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Oct 26 17:10:22 CEST 2006]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class EstadosproduccionManager
    extends BaseEstadosproduccionManager
{


//Borrado de un elemento
	public static boolean borraEstadosproduccion(int idBorrar) {

		Criteria c=new Criteria();
		c.add(EstadosproduccionPeer.IDESTADOPRODUCCION, idBorrar);
		boolean bRet = false;
		try {
			EstadosproduccionPeer.doDelete(c);
			bRet = true;
		} catch (TorqueException e) {
			logger.info("No se ha podido borrar en la tabla Estadosproduccion");
			e.printStackTrace();
			bRet = false;
		}
		return bRet;
	}

}


