package net.idtoki.adimde.manager;

import org.apache.torque.TorqueException;
import org.apache.torque.util.Criteria;

import com.workingdogs.village.DataSetException;

import net.idtoki.adimde.model.OperariosPeer;
import net.idtoki.adimde.model.TurnosPeer;
import net.idtoki.adimde.model.PartesPeer;
import net.idtoki.adimde.model.PerfilturnoPeer;
import net.idtoki.adimde.model.PerfilesPeer;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Oct 02 10:34:00 CEST 2006]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class PartesManager
    extends BasePartesManager
{


//Borrado de un elemento
	public static boolean borraPartes(int idBorrar) {

		Criteria c=new Criteria();
		c.add(PartesPeer.IDPARTE, idBorrar);
		boolean bRet = false;
		try {
			PartesPeer.doDelete(c);
			bRet = true;
		} catch (TorqueException e) {
			logger.info("No se ha podido borrar en la tabla Partes");
			e.printStackTrace();
			bRet = false;
		}
		return bRet;
	}

	public static double getManoObraPartes(int idParte) throws TorqueException,DataSetException
	{
		Criteria c=new Criteria();
		c.add(PartesPeer.IDPARTE,idParte);
		c.addJoin(OperariosPeer.IDOPERARIO,PartesPeer.IDOPERARIO);
		c.addJoin(TurnosPeer.IDTURNO,PartesPeer.IDTURNO);
		c.addJoin(PerfilesPeer.IDPERFIL,PerfilturnoPeer.IDPERFIL);
		c.addJoin(TurnosPeer.IDTURNO,PerfilturnoPeer.IDTURNO);		
		c.addJoin(PerfilesPeer.IDPERFIL,OperariosPeer.IDPERFIL);		
		c.addSelectColumn("SUM(" + PartesPeer.HORAS+ "*" + PerfilturnoPeer.VALORCOSTE + ")");
		java.util.List result = PerfilturnoPeer.doSelectVillageRecords(c);
		com.workingdogs.village.Record record = (com.workingdogs.village.Record) result.get(0);
		return record.getValue(1).asDouble();			
	}		
	
}


