package net.idtoki.adimde.manager;

import org.apache.torque.TorqueException;
import org.apache.torque.util.Criteria;

import net.idtoki.adimde.model.UnidadesmedidaPeer;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Oct 26 17:10:22 CEST 2006]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class UnidadesmedidaManager
    extends BaseUnidadesmedidaManager
{


//Borrado de un elemento
	public static boolean borraUnidadesmedida(int idBorrar) {

		Criteria c=new Criteria();
		c.add(UnidadesmedidaPeer.IDUNIDADMEDIDA, idBorrar);
		boolean bRet = false;
		try {
			UnidadesmedidaPeer.doDelete(c);
			bRet = true;
		} catch (TorqueException e) {
			logger.info("No se ha podido borrar en la tabla Unidadesmedida");
			e.printStackTrace();
			bRet = false;
		}
		return bRet;
	}

}


