package net.idtoki.adimde.controller;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.ResourceBundle;
import java.util.logging.Logger;

import javax.servlet.ServletConfig;
import javax.servlet.ServletContext;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.xml.transform.Source;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.stream.StreamSource;

import org.apache.torque.TorqueException;
import org.apache.torque.util.Criteria;

import net.idtoki.adimde.manager.CentrosManager;
import net.idtoki.adimde.group.CentrosGroupBean;
import net.idtoki.adimde.helper.CentrosHelper;
import net.idtoki.adimde.model.CentrosPeer;
import net.idtoki.adimde.model.Centros;

import net.idtoki.adimde.manager.LocalidadesManager;
import net.idtoki.adimde.group.LocalidadesGroupBean;
import net.idtoki.adimde.model.LocalidadesPeer;
import net.idtoki.adimde.helper.LocalidadesHelper;

import net.idtoki.adimde.helper.ProduccionesHelper;


import net.zylk.tools.ajax.AjaxUtils;
import net.zylk.tools.ajax.AjaxUtils.DinamicGridBean;
import net.zylk.tools.format.FormatUtils;
import net.zylk.tools.pdf.PdfUtils;
import net.zylk.tools.xml.XmlUtils;
import net.zylk.torque.TorqueUtils;
import net.zylk.web.WebUtils;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Oct 02 10:34:00 CEST 2006]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
 
 
public class CentrosController
    extends net.idtoki.adimde.controller.BaseCentrosController
{
 private static final Logger logger = Logger.getLogger("net.idtoki.adimde.controller.CentrosController");
 private TransformerFactory tFactory = TransformerFactory.newInstance();
 private Transformer centros_transformer = null;  
 private Transformer centross_transformer = null; 

 public void init(ServletConfig config)
 {
	super.init();
	ResourceBundle resource = ResourceBundle.getBundle("net/idtoki/adimde/app/config/app-config");
	File centros = new File(resource.getString("app.xsl.templates.dir")+"/PdfCentros.xslt");
	Source xslSource = new StreamSource(centros);
	File centross = new File(resource.getString("app.xsl.templates.dir")+"/PdfListaCentros.xslt");
	Source xslSourceT = new StreamSource(centross); 	  
	try{
		centros_transformer = tFactory.newTransformer(xslSource);
		centross_transformer = tFactory.newTransformer(xslSourceT);			  
	}catch (Exception e){
	  e.printStackTrace();
	}
 }


//Función para la inserción/actualización de registros

public void serviceAddCentros(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 //Con esto se consigue transformar el request a UTF
	 //para temas de acentos y otros caracteres
	 utf8RequestService(request);

	 //recojo los parametros del formulario y doy de alta un nuevo elmento
	 try
	 {
		 Centros elCentros = CentrosHelper.createObj(request);
		 CentrosGroupBean gbCentros = new CentrosGroupBean();
		 gbCentros.setElemento(elCentros);
		 gbCentros.save();
	 }
	 catch(TorqueException te)
	 {
		 response.sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
	 }
 }


//Función para la eliminación de un registro
//este método invoca al método public void deleteCentros(int idBorrar)
//definido en el CentrosManager
 public void serviceDeleteCentros(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 int idBorrar=-1;
	 idBorrar=WebUtils.getintParam(request, "borrarId");
	 if (idBorrar!=-1)
 		 if (CentrosManager.borraCentros(idBorrar))
			 WebUtils.writeXmlResponse(response,XmlUtils.buildXmlOKResponse("ISO-8859-1"));
		 else
			 WebUtils.writeXmlResponse(response,XmlUtils.buildXmlNotOKResponse("ISO-8859-1"));			 
 }


// Funciones para las ordenaciones y filtrados de información

 private Criteria ordenacion(Criteria c,String CampoOrdenacion,String OrdenOrdenacion) 
 { 
 	if((OrdenOrdenacion != null )&& (OrdenOrdenacion.compareTo("ASC")==0))
 		if ((CampoOrdenacion != null))
 		{
 			c.addAscendingOrderByColumn(CampoOrdenacion.toString());
 		}
 	if  ((OrdenOrdenacion != null) && (OrdenOrdenacion.compareTo("DESC")==0))
 		if ((CampoOrdenacion != null))
		{
 			c.addDescendingOrderByColumn(CampoOrdenacion.toString());
 		}
 	return c;
 }

private Criteria filtro(Criteria c,int filtro) 
{ 
	String cadena = null;
	 switch (filtro)
	 {
	 case 1:
		  //Caso uno de Filtrado
		  //c.add(Campo,valor);
		  break;
	 case 2:
		  //Caso dos de Filtrado
		  //c.add(Campo,valor);
		  break;
	 default:
		 //caso por defecto
		 break;
	 }
	return c;
}

 public StringBuffer replaceStringBuffer (StringBuffer strBA, String strOrigen, String strDestino) 
 {
	 return new StringBuffer(strBA.toString().replaceAll(strOrigen,strDestino));
 }

 private Criteria criteriaCentrosTableContent(HttpServletRequest request,Criteria c) throws IOException, ServletException
 {
 	String param = "";	 
	 param =  WebUtils.getStringParam(request, new LocalidadesHelper().getIdlocalidadName());
	 if(param != null)
		 TorqueUtils.addEqualCriteria(c,CentrosPeer.IDLOCALIDAD,param);
	  String paramSortCol =  WebUtils.getStringParam(request, "sort_col");
	  String paramSortDir =  WebUtils.getStringParam(request, "sort_dir");
	  int paramFiltro =  WebUtils.getintParam(request, "filtro");
	  c = ordenacion(c,paramSortCol,paramSortDir);
	  c = filtro(c,paramFiltro);

 	  return c;
 } 
 
 public String getPathElementCentros(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
	 Criteria c= new Criteria();
	 String strPath = "";
	 int claveId=-1;
	 int claveFkId=-1;	 
	 claveId=WebUtils.getintParam(request, "centros.IDCENTRO");
	 if (claveId!=-1)
	 {
		c.add(CentrosPeer.IDCENTRO, claveId);
		CentrosGroupBean trgb = CentrosManager.getCentross(c);							
		strPath = trgb.getCentros(0).getPathCentrosParsed(request.getQueryString());
	 }
	 return "<path>" + strPath + "</path>";
 } 
 
 public String getPathTableContentCentros(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
	 Criteria c= new Criteria();
	 String strPath = "";
	 int claveId=-1;	 
	 claveId=WebUtils.getintParam(request, "localidades.IDLOCALIDAD");
	 if(claveId != -1){
		 strPath = LocalidadesManager.getLocalidades(claveId).getPathLocalidadesParsed(request.getQueryString());
	 }		 	 
	 return "<path>" + strPath + "</path>";
 }  


public void  serviceCentrosTableContent(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
	 utf8RequestService(request);
	 int numElemPedidosBD = 40;
	 int gap = 0;//gap = viewedRows - numElemVisiblesUltPag	  
	 DinamicGridBean dgb = WebUtils.getDinamicGridBeanParam(request,numElemPedidosBD,gap); 
	 Criteria c =CentrosManager.buildSearchCriteria(dgb);
	 c =criteriaCentrosTableContent(request,c);	 
	 CentrosGroupBean cgb = CentrosManager.getCentross(c);
	 dgb.setTotalSize(cgb.getTotalSize());
	  
	 String[] methodos= new String[] {
		CentrosHelper.NOMBRE_GET_METHOD_NAME+"CentrosParsed"
		,CentrosHelper.DIRECCION_GET_METHOD_NAME+"CentrosParsed"
		//,CentrosHelper.CP_GET_METHOD_NAME+"CentrosParsed"
		,CentrosHelper.IDLOCALIDAD_GET_METHOD_NAME+"CentrosParsed"
		,CentrosHelper.TELEFONO_GET_METHOD_NAME+"CentrosParsed"
		//,CentrosHelper.FAX_GET_METHOD_NAME+"CentrosParsed"
		//,CentrosHelper.CONTACTO_GET_METHOD_NAME+"CentrosParsed"
		//,CentrosHelper.EMAIL_GET_METHOD_NAME+"CentrosParsed"
		,"getHijosProduccionesCentros"
		,"getEditCentros"
		,"getDeleteCentros"
	};
	 
	 StringBuffer cadena=null;
	 cadena = AjaxUtils.buildXmlAjaxResponseTableContentFromListObj(cgb.getAlmacen(),methodos,CentrosHelper.IDCENTRO_GET_METHOD_NAME, dgb,"ISO-8859-1"); 
	 cadena.insert(cadena.indexOf("</ajax-response>"),"<response type='object' id='divPath'>" + getPathTableContentCentros(request,response) + "</response>");
	 xmlResponseService(response,cadena); 
 }  

 public void serviceCentrosUlContent(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
	 String[] methodos= new String[] {
	 		"getULContentCentrosParsed"
			 };
	 String param =  WebUtils.getStringParam(request, "value");
	 if(param==null || param.length() <= 0)
		 param =  WebUtils.getStringParam(request, new ProduccionesHelper().getIdcentroName());
	 	 
	 CentrosGroupBean mgb = CentrosManager.getCentross(CentrosManager.buildSearchCriteria(param));
	 simpleResponseService(response, AjaxUtils.buildAjaxULContentFromListObj(mgb.getAlmacen(),methodos, CentrosHelper.COMPLEX_ID_GET_METHOD,"Centros"));
 } 



 public void serviceCentrosElement(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
  StringBuffer cadena=null;
  Criteria c= new Criteria();
  int claveId=-1;
  claveId=WebUtils.getintParam(request, "centros.IDCENTRO");
  if (claveId!=-1)
  {
	  c.add(CentrosPeer.IDCENTRO, claveId);
  }
  c.addAscendingOrderByColumn(CentrosPeer.IDCENTRO);
  CentrosGroupBean trgb = CentrosManager.getCentross(c);
  
  if (trgb.getTotalSize()!=0)
  {
	  String [] parametros={
		CentrosHelper.IDCENTRO_GET_METHOD_NAME
		,CentrosHelper.NOMBRE_GET_METHOD_NAME+"CentrosParsed"
		,CentrosHelper.DIRECCION_GET_METHOD_NAME+"CentrosParsed"
		,CentrosHelper.CP_GET_METHOD_NAME+"CentrosParsed"
		,CentrosHelper.IDLOCALIDAD_GET_METHOD_NAME+"CentrosParsed"
		,CentrosHelper.TELEFONO_GET_METHOD_NAME+"CentrosParsed"
		,CentrosHelper.FAX_GET_METHOD_NAME+"CentrosParsed"
		,CentrosHelper.CONTACTO_GET_METHOD_NAME+"CentrosParsed"
		,CentrosHelper.EMAIL_GET_METHOD_NAME+"CentrosParsed"
	  };
	  cadena=trgb.buildXml(parametros,null,"ISO-8859-1");	
	  cadena.insert(cadena.indexOf("</result>"),getPathElementCentros(request,response));  
  }
  xmlResponseService(response, cadena);
 } 
 

 protected StringBuffer updateIdcentroResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(CentrosManager.getCentros(Integer.parseInt(a.get(0).toString())).getIdcentroCentrosParsed());
 }  
 

 protected StringBuffer updateNombreResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(CentrosManager.getCentros(Integer.parseInt(a.get(0).toString())).getNombreCentrosParsed());
 }  
 

 protected StringBuffer updateDireccionResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(CentrosManager.getCentros(Integer.parseInt(a.get(0).toString())).getDireccionCentrosParsed());
 }  
 

 protected StringBuffer updateCpResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(CentrosManager.getCentros(Integer.parseInt(a.get(0).toString())).getCpCentrosParsed());
 }  
 

 protected StringBuffer updateIdlocalidadResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(CentrosManager.getCentros(Integer.parseInt(a.get(0).toString())).getIdlocalidadCentrosParsed());
 }  
 

 protected StringBuffer updateTelefonoResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(CentrosManager.getCentros(Integer.parseInt(a.get(0).toString())).getTelefonoCentrosParsed());
 }  
 

 protected StringBuffer updateFaxResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(CentrosManager.getCentros(Integer.parseInt(a.get(0).toString())).getFaxCentrosParsed());
 }  
 

 protected StringBuffer updateContactoResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(CentrosManager.getCentros(Integer.parseInt(a.get(0).toString())).getContactoCentrosParsed());
 }  
 

 protected StringBuffer updateEmailResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(CentrosManager.getCentros(Integer.parseInt(a.get(0).toString())).getEmailCentrosParsed());
 }  
 
 
 
 public void serviceCentrosLocalidades(HttpServletRequest request, HttpServletResponse response) throws IOException, TorqueException, ServletException
 {
  String cadena=null;
  Criteria c= new Criteria();
  int claveId=-1;
  claveId=WebUtils.getintParam(request, "localidades.IDLOCALIDAD");
  if (claveId!=-1)
  {
	  c.add(LocalidadesPeer.IDLOCALIDAD, claveId);
  }
  c.addAscendingOrderByColumn(LocalidadesPeer.IDLOCALIDAD);
  LocalidadesGroupBean trgb = LocalidadesManager.getLocalidadess(c);
  
  if (trgb.getTotalSize()!=0)
  {
	  cadena = "<?xml version=\"1.0\" encoding=\"ISO-8859-1\" ?>";
	  cadena = cadena + "<result><centros.IDLOCALIDAD>" + trgb.getLocalidades(0).getULContentLocalidadesParsed()  + "</centros.IDLOCALIDAD></result>";
  }
  
  xmlResponseService(response, new StringBuffer(cadena));
 }  
  			

 public void serviceGetCentrosDetallePdf(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
	 String[] getMethodos= new String[] {
		CentrosHelper.IDCENTRO_GET_METHOD_NAME
		,CentrosHelper.NOMBRE_GET_METHOD_NAME+"CentrosParsed"
		,CentrosHelper.DIRECCION_GET_METHOD_NAME+"CentrosParsed"
		,CentrosHelper.CP_GET_METHOD_NAME+"CentrosParsed"
		,CentrosHelper.IDLOCALIDAD_GET_METHOD_NAME+"CentrosParsed"
		,CentrosHelper.TELEFONO_GET_METHOD_NAME+"CentrosParsed"
		,CentrosHelper.FAX_GET_METHOD_NAME+"CentrosParsed"
		,CentrosHelper.CONTACTO_GET_METHOD_NAME+"CentrosParsed"
		,CentrosHelper.EMAIL_GET_METHOD_NAME+"CentrosParsed"
			 };
	  
	 
	 CentrosGroupBean tgb = new CentrosGroupBean();
	 try
	{
		tgb.setElemento(CentrosHelper.getCentros(request));
	} catch (TorqueException e)
	{
		logger.severe(e.getMessage());
	}
	
	 byte[] content =  PdfUtils.getBytes(replaceStringBuffer(tgb.buildXml(getMethodos, null,"ISO-8859-1"),"n/a"," "), centros_transformer,"ISO-8859-1");
	 response.addHeader("content-disposition","attachment;filename=Centros.pdf");
	 response.setContentType("application/pdf");
	 response.setHeader("Cache-Control", "");//para que funcione en IE
	 response.setContentLength(content.length);
	 response.getOutputStream().write(content);
	 response.getOutputStream().flush();  
	 response.getOutputStream().close();
	
 }  

 public void serviceCentrosTableContentPdf(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
  	utf8RequestService(request);
  	Criteria c= new Criteria();
  	String paramQuery =  WebUtils.getStringParam(request, "query");
  	if ((paramQuery != null)&& (paramQuery.compareTo("")!=0) )
		c = CentrosManager.buildSearchCriteria(paramQuery);   
  	c =criteriaCentrosTableContent(request,c);	  
  	CentrosGroupBean tgb = CentrosManager.getCentross(c);
  
  	String[] methodos= new String[] {	
		CentrosHelper.NOMBRE_GET_METHOD_NAME+"CentrosParsed"
		,CentrosHelper.DIRECCION_GET_METHOD_NAME+"CentrosParsed"
		//,CentrosHelper.CP_GET_METHOD_NAME+"CentrosParsed"
		,CentrosHelper.IDLOCALIDAD_GET_METHOD_NAME+"CentrosParsed"
		,CentrosHelper.TELEFONO_GET_METHOD_NAME+"CentrosParsed"
		//,CentrosHelper.FAX_GET_METHOD_NAME+"CentrosParsed"
		//,CentrosHelper.CONTACTO_GET_METHOD_NAME+"CentrosParsed"
		//,CentrosHelper.EMAIL_GET_METHOD_NAME+"CentrosParsed"
			};
  
	 byte[] content =  PdfUtils.getBytes(replaceStringBuffer(tgb.buildXml(methodos, null,"ISO-8859-1"),"n/a"," "), centross_transformer,"ISO-8859-1");
	 response.addHeader("content-disposition","attachment;filename=ListaCentros.pdf");
	 response.setContentType("application/pdf");
	 response.setHeader("Cache-Control", "");//para que funcione en IE
	 response.setContentLength(content.length);
	 response.getOutputStream().write(content);
	 response.getOutputStream().flush();  
	 response.getOutputStream().close();
 }

}


