package net.idtoki.adimde.controller;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.ResourceBundle;
import java.util.logging.Logger;

import javax.servlet.ServletConfig;
import javax.servlet.ServletContext;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.xml.transform.Source;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.stream.StreamSource;

import org.apache.torque.TorqueException;
import org.apache.torque.util.Criteria;

import net.idtoki.adimde.manager.ComposicionesManager;
import net.idtoki.adimde.group.ComposicionesGroupBean;
import net.idtoki.adimde.helper.ComposicionesHelper;
import net.idtoki.adimde.model.ComposicionesPeer;
import net.idtoki.adimde.model.Composiciones;

import net.idtoki.adimde.manager.MaterialesManager;
import net.idtoki.adimde.group.MaterialesGroupBean;
import net.idtoki.adimde.model.MaterialesPeer;
import net.idtoki.adimde.helper.MaterialesHelper;
import net.idtoki.adimde.manager.ProductosManager;
import net.idtoki.adimde.group.ProductosGroupBean;
import net.idtoki.adimde.model.ProductosPeer;
import net.idtoki.adimde.helper.ProductosHelper;



import net.zylk.tools.ajax.AjaxUtils;
import net.zylk.tools.ajax.AjaxUtils.DinamicGridBean;
import net.zylk.tools.format.FormatUtils;
import net.zylk.tools.pdf.PdfUtils;
import net.zylk.tools.xml.XmlUtils;
import net.zylk.torque.TorqueUtils;
import net.zylk.web.WebUtils;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Oct 02 10:34:00 CEST 2006]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
 
 
public class ComposicionesController
    extends net.idtoki.adimde.controller.BaseComposicionesController
{
 private static final Logger logger = Logger.getLogger("net.idtoki.adimde.controller.ComposicionesController");
 private TransformerFactory tFactory = TransformerFactory.newInstance();
 private Transformer composiciones_transformer = null;  
 private Transformer composicioness_transformer = null; 

 public void init(ServletConfig config)
 {
	super.init();
	ResourceBundle resource = ResourceBundle.getBundle("net/idtoki/adimde/app/config/app-config");
	File composiciones = new File(resource.getString("app.xsl.templates.dir")+"/PdfComposiciones.xslt");
	Source xslSource = new StreamSource(composiciones);
	File composicioness = new File(resource.getString("app.xsl.templates.dir")+"/PdfListaComposiciones.xslt");
	Source xslSourceT = new StreamSource(composicioness); 	  
	try{
		composiciones_transformer = tFactory.newTransformer(xslSource);
		composicioness_transformer = tFactory.newTransformer(xslSourceT);			  
	}catch (Exception e){
	  e.printStackTrace();
	}
 }


//Función para la inserción/actualización de registros

public void serviceAddComposiciones(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 //Con esto se consigue transformar el request a UTF
	 //para temas de acentos y otros caracteres
	 utf8RequestService(request);

	 //recojo los parametros del formulario y doy de alta un nuevo elmento
	 try
	 {
		 Composiciones elComposiciones = ComposicionesHelper.createObj(request);
		 ComposicionesGroupBean gbComposiciones = new ComposicionesGroupBean();
		 gbComposiciones.setElemento(elComposiciones);
		 gbComposiciones.save();
	 }
	 catch(TorqueException te)
	 {
		 response.sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
	 }
 }


//Función para la eliminación de un registro
//este método invoca al método public void deleteComposiciones(int idBorrar)
//definido en el ComposicionesManager
 public void serviceDeleteComposiciones(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 int idBorrar=-1;
	 idBorrar=WebUtils.getintParam(request, "borrarId");
	 if (idBorrar!=-1)
 		 if (ComposicionesManager.borraComposiciones(idBorrar))
			 WebUtils.writeXmlResponse(response,XmlUtils.buildXmlOKResponse("ISO-8859-1"));
		 else
			 WebUtils.writeXmlResponse(response,XmlUtils.buildXmlNotOKResponse("ISO-8859-1"));			 
 }


// Funciones para las ordenaciones y filtrados de información

 private Criteria ordenacion(Criteria c,String CampoOrdenacion,String OrdenOrdenacion) 
 { 
 	if((OrdenOrdenacion != null )&& (OrdenOrdenacion.compareTo("ASC")==0))
 		if ((CampoOrdenacion != null))
 		{
 			c.addAscendingOrderByColumn(CampoOrdenacion.toString());
 		}
 	if  ((OrdenOrdenacion != null) && (OrdenOrdenacion.compareTo("DESC")==0))
 		if ((CampoOrdenacion != null))
		{
 			c.addDescendingOrderByColumn(CampoOrdenacion.toString());
 		}
 	return c;
 }

private Criteria filtro(Criteria c,int filtro) 
{ 
	String cadena = null;
	 switch (filtro)
	 {
	 case 1:
		  //Caso uno de Filtrado
		  //c.add(Campo,valor);
		  break;
	 case 2:
		  //Caso dos de Filtrado
		  //c.add(Campo,valor);
		  break;
	 default:
		 //caso por defecto
		 break;
	 }
	return c;
}

 public StringBuffer replaceStringBuffer (StringBuffer strBA, String strOrigen, String strDestino) 
 {
	 return new StringBuffer(strBA.toString().replaceAll(strOrigen,strDestino));
 }

 private Criteria criteriaComposicionesTableContent(HttpServletRequest request,Criteria c) throws IOException, ServletException
 {
 	String param = "";	 
	 param =  WebUtils.getStringParam(request, new MaterialesHelper().getIdmaterialName());
	 if(param != null)
		 TorqueUtils.addEqualCriteria(c,ComposicionesPeer.IDMATERIAL,param);
	 param =  WebUtils.getStringParam(request, new ProductosHelper().getIdproductoName());
	 if(param != null)
		 TorqueUtils.addEqualCriteria(c,ComposicionesPeer.IDPRODUCTO,param);
	  String paramSortCol =  WebUtils.getStringParam(request, "sort_col");
	  String paramSortDir =  WebUtils.getStringParam(request, "sort_dir");
	  int paramFiltro =  WebUtils.getintParam(request, "filtro");
	  c = ordenacion(c,paramSortCol,paramSortDir);
	  c = filtro(c,paramFiltro);

 	  return c;
 } 
 
 public String getPathElementComposiciones(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
	 Criteria c= new Criteria();
	 String strPath = "";
	 int claveId=-1;
	 int claveFkId=-1;	 
	 claveId=WebUtils.getintParam(request, "composiciones.IDCOMPOSICION");
	 if (claveId!=-1)
	 {
		c.add(ComposicionesPeer.IDCOMPOSICION, claveId);
		ComposicionesGroupBean trgb = ComposicionesManager.getComposicioness(c);							
		strPath = trgb.getComposiciones(0).getPathComposicionesParsed(request.getQueryString());
	 }
	 return "<path>" + strPath + "</path>";
 } 
 
 public String getPathTableContentComposiciones(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
	 Criteria c= new Criteria();
	 String strPath = "";
	 int claveId=-1;	 
	 claveId=WebUtils.getintParam(request, "materiales.IDMATERIAL");
	 if(claveId != -1){
		 strPath = MaterialesManager.getMateriales(claveId).getPathMaterialesParsed(request.getQueryString());
	 }		 	 
	 claveId=WebUtils.getintParam(request, "productos.IDPRODUCTO");
	 if(claveId != -1){
		 strPath = ProductosManager.getProductos(claveId).getPathProductosParsed(request.getQueryString());
	 }		 	 
	 return "<path>" + strPath + "</path>";
 }  


public void  serviceComposicionesTableContent(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
	 utf8RequestService(request);
	 int numElemPedidosBD = 40;
	 int gap = 0;//gap = viewedRows - numElemVisiblesUltPag	  
	 DinamicGridBean dgb = WebUtils.getDinamicGridBeanParam(request,numElemPedidosBD,gap); 
	 Criteria c =ComposicionesManager.buildSearchCriteria(dgb);
	 c =criteriaComposicionesTableContent(request,c);	 
	 ComposicionesGroupBean cgb = ComposicionesManager.getComposicioness(c);
	 dgb.setTotalSize(cgb.getTotalSize());
	  
	 String[] methodos= new String[] {
		ComposicionesHelper.IDMATERIAL_GET_METHOD_NAME+"ComposicionesParsed"
		,ComposicionesHelper.IDPRODUCTO_GET_METHOD_NAME+"ComposicionesParsed"
		,ComposicionesHelper.UNIDADES_GET_METHOD_NAME+"ComposicionesParsed"
		,"getEditComposiciones"
		,"getDeleteComposiciones"
	};
	 
	 StringBuffer cadena=null;
	 cadena = AjaxUtils.buildXmlAjaxResponseTableContentFromListObj(cgb.getAlmacen(),methodos,ComposicionesHelper.IDCOMPOSICION_GET_METHOD_NAME, dgb,"ISO-8859-1"); 
	 cadena.insert(cadena.indexOf("</ajax-response>"),"<response type='object' id='divPath'>" + getPathTableContentComposiciones(request,response) + "</response>");
	 xmlResponseService(response,cadena); 
 }  

 public void serviceComposicionesUlContent(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
	 String[] methodos= new String[] {
	 		"getULContentComposicionesParsed"
			 };
	 String param =  WebUtils.getStringParam(request, "value");
	 	 
	 ComposicionesGroupBean mgb = ComposicionesManager.getComposicioness(ComposicionesManager.buildSearchCriteria(param));
	 simpleResponseService(response, AjaxUtils.buildAjaxULContentFromListObj(mgb.getAlmacen(),methodos, ComposicionesHelper.COMPLEX_ID_GET_METHOD,"Composiciones"));
 } 



 public void serviceComposicionesElement(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
  StringBuffer cadena=null;
  Criteria c= new Criteria();
  int claveId=-1;
  claveId=WebUtils.getintParam(request, "composiciones.IDCOMPOSICION");
  if (claveId!=-1)
  {
	  c.add(ComposicionesPeer.IDCOMPOSICION, claveId);
  }
  c.addAscendingOrderByColumn(ComposicionesPeer.IDCOMPOSICION);
  ComposicionesGroupBean trgb = ComposicionesManager.getComposicioness(c);
  
  if (trgb.getTotalSize()!=0)
  {
	  String [] parametros={
		ComposicionesHelper.IDCOMPOSICION_GET_METHOD_NAME
		,ComposicionesHelper.IDMATERIAL_GET_METHOD_NAME+"ComposicionesParsed"
		,ComposicionesHelper.IDPRODUCTO_GET_METHOD_NAME+"ComposicionesParsed"
		,ComposicionesHelper.UNIDADES_GET_METHOD_NAME+"ComposicionesParsed"
		,"getCosteMaterialesComposicionesParsed"
	  };
	  cadena=trgb.buildXml(parametros,null,"ISO-8859-1");	
	  cadena.insert(cadena.indexOf("</result>"),getPathElementComposiciones(request,response));  
  }
  xmlResponseService(response, cadena);
 } 
 

 protected StringBuffer updateIdcomposicionResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(ComposicionesManager.getComposiciones(Integer.parseInt(a.get(0).toString())).getIdcomposicionComposicionesParsed());
 }  
 

 protected StringBuffer updateIdmaterialResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(ComposicionesManager.getComposiciones(Integer.parseInt(a.get(0).toString())).getIdmaterialComposicionesParsed());
 }  
 

 protected StringBuffer updateIdproductoResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(ComposicionesManager.getComposiciones(Integer.parseInt(a.get(0).toString())).getIdproductoComposicionesParsed());
 }  
 

 protected StringBuffer updateUnidadesResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(ComposicionesManager.getComposiciones(Integer.parseInt(a.get(0).toString())).getUnidadesComposicionesParsed());
 }  
 
 
 
 public void serviceComposicionesMateriales(HttpServletRequest request, HttpServletResponse response) throws IOException, TorqueException, ServletException
 {
  String cadena=null;
  Criteria c= new Criteria();
  int claveId=-1;
  claveId=WebUtils.getintParam(request, "materiales.IDMATERIAL");
  if (claveId!=-1)
  {
	  c.add(MaterialesPeer.IDMATERIAL, claveId);
  }
  c.addAscendingOrderByColumn(MaterialesPeer.IDMATERIAL);
  MaterialesGroupBean trgb = MaterialesManager.getMaterialess(c);
  
  if (trgb.getTotalSize()!=0)
  {
	  cadena = "<?xml version=\"1.0\" encoding=\"ISO-8859-1\" ?>";
	  cadena = cadena + "<result><composiciones.IDMATERIAL>" + trgb.getMateriales(0).getULContentMaterialesParsed()  + "</composiciones.IDMATERIAL></result>";
  }
  
  xmlResponseService(response, new StringBuffer(cadena));
 }  
  			
 
 public void serviceComposicionesProductos(HttpServletRequest request, HttpServletResponse response) throws IOException, TorqueException, ServletException
 {
  String cadena=null;
  Criteria c= new Criteria();
  int claveId=-1;
  claveId=WebUtils.getintParam(request, "productos.IDPRODUCTO");
  if (claveId!=-1)
  {
	  c.add(ProductosPeer.IDPRODUCTO, claveId);
  }
  c.addAscendingOrderByColumn(ProductosPeer.IDPRODUCTO);
  ProductosGroupBean trgb = ProductosManager.getProductoss(c);
  
  if (trgb.getTotalSize()!=0)
  {
	  cadena = "<?xml version=\"1.0\" encoding=\"ISO-8859-1\" ?>";
	  cadena = cadena + "<result><composiciones.IDPRODUCTO>" + trgb.getProductos(0).getULContentProductosParsed()  + "</composiciones.IDPRODUCTO></result>";
  }
  
  xmlResponseService(response, new StringBuffer(cadena));
 }  
  			

 public void serviceGetComposicionesDetallePdf(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
	 String[] getMethodos= new String[] {
		ComposicionesHelper.IDCOMPOSICION_GET_METHOD_NAME
		,ComposicionesHelper.IDMATERIAL_GET_METHOD_NAME+"ComposicionesParsed"
		,ComposicionesHelper.IDPRODUCTO_GET_METHOD_NAME+"ComposicionesParsed"
		,ComposicionesHelper.UNIDADES_GET_METHOD_NAME+"ComposicionesParsed"
		,"getCosteMaterialesComposicionesParsed"		
			 };
	  
	 
	 ComposicionesGroupBean tgb = new ComposicionesGroupBean();
	 try
	{
		tgb.setElemento(ComposicionesHelper.getComposiciones(request));
	} catch (TorqueException e)
	{
		logger.severe(e.getMessage());
	}
	
	 byte[] content =  PdfUtils.getBytes(replaceStringBuffer(tgb.buildXml(getMethodos, null,"ISO-8859-1"),"n/a"," "), composiciones_transformer,"ISO-8859-1");
	 response.addHeader("content-disposition","attachment;filename=Composiciones.pdf");
	 response.setContentType("application/pdf");
	 response.setHeader("Cache-Control", "");//para que funcione en IE
	 response.setContentLength(content.length);
	 response.getOutputStream().write(content);
	 response.getOutputStream().flush();  
	 response.getOutputStream().close();
	
 }  

 public void serviceComposicionesTableContentPdf(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
  	utf8RequestService(request);
  	Criteria c= new Criteria();
  	String paramQuery =  WebUtils.getStringParam(request, "query");
  	if ((paramQuery != null)&& (paramQuery.compareTo("")!=0) )
		c = ComposicionesManager.buildSearchCriteria(paramQuery);   
  	c =criteriaComposicionesTableContent(request,c);	  
  	ComposicionesGroupBean tgb = ComposicionesManager.getComposicioness(c);
  
  	String[] methodos= new String[] {	
		ComposicionesHelper.IDMATERIAL_GET_METHOD_NAME+"ComposicionesParsed"
		,ComposicionesHelper.IDPRODUCTO_GET_METHOD_NAME+"ComposicionesParsed"
		,ComposicionesHelper.UNIDADES_GET_METHOD_NAME+"ComposicionesParsed"
			};
  
	 byte[] content =  PdfUtils.getBytes(replaceStringBuffer(tgb.buildXml(methodos, null,"ISO-8859-1"),"n/a"," "), composicioness_transformer,"ISO-8859-1");
	 response.addHeader("content-disposition","attachment;filename=ListaComposiciones.pdf");
	 response.setContentType("application/pdf");
	 response.setHeader("Cache-Control", "");//para que funcione en IE
	 response.setContentLength(content.length);
	 response.getOutputStream().write(content);
	 response.getOutputStream().flush();  
	 response.getOutputStream().close();
 }

}


