package net.idtoki.adimde.controller;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.ResourceBundle;
import java.util.logging.Logger;

import javax.servlet.ServletConfig;
import javax.servlet.ServletContext;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.xml.transform.Source;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.stream.StreamSource;

import org.apache.torque.TorqueException;
import org.apache.torque.util.Criteria;

import net.idtoki.adimde.manager.EstadosproduccionManager;
import net.idtoki.adimde.group.EstadosproduccionGroupBean;
import net.idtoki.adimde.helper.EstadosproduccionHelper;
import net.idtoki.adimde.model.EstadosproduccionPeer;
import net.idtoki.adimde.model.Estadosproduccion;


import net.idtoki.adimde.helper.ProduccionesHelper;


import net.zylk.tools.ajax.AjaxUtils;
import net.zylk.tools.ajax.AjaxUtils.DinamicGridBean;
import net.zylk.tools.format.FormatUtils;
import net.zylk.tools.pdf.PdfUtils;
import net.zylk.tools.xml.XmlUtils;
import net.zylk.torque.TorqueUtils;
import net.zylk.web.WebUtils;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Oct 26 17:10:22 CEST 2006]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
 
 
public class EstadosproduccionController
    extends net.idtoki.adimde.controller.BaseEstadosproduccionController
{
 private static final Logger logger = Logger.getLogger("net.idtoki.adimde.controller.EstadosproduccionController");
 private TransformerFactory tFactory = TransformerFactory.newInstance();
 private Transformer estadosproduccion_transformer = null;  
 private Transformer estadosproduccions_transformer = null; 

 public void init(ServletConfig config)
 {
	super.init();
	ResourceBundle resource = ResourceBundle.getBundle("net/idtoki/adimde/app/config/app-config");
	File estadosproduccion = new File(resource.getString("app.xsl.templates.dir")+"/PdfEstadosproduccion.xslt");
	Source xslSource = new StreamSource(estadosproduccion);
	File estadosproduccions = new File(resource.getString("app.xsl.templates.dir")+"/PdfListaEstadosproduccion.xslt");
	Source xslSourceT = new StreamSource(estadosproduccions); 	  
	try{
		estadosproduccion_transformer = tFactory.newTransformer(xslSource);
		estadosproduccions_transformer = tFactory.newTransformer(xslSourceT);			  
	}catch (Exception e){
	  e.printStackTrace();
	}
 }


//Función para la inserción/actualización de registros

public void serviceAddEstadosproduccion(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 //Con esto se consigue transformar el request a UTF
	 //para temas de acentos y otros caracteres
	 utf8RequestService(request);

	 //recojo los parametros del formulario y doy de alta un nuevo elmento
	 try
	 {
		 Estadosproduccion elEstadosproduccion = EstadosproduccionHelper.createObj(request);
		 EstadosproduccionGroupBean gbEstadosproduccion = new EstadosproduccionGroupBean();
		 gbEstadosproduccion.setElemento(elEstadosproduccion);
		 gbEstadosproduccion.save();
	 }
	 catch(TorqueException te)
	 {
		 response.sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
	 }
 }


//Función para la eliminación de un registro
//este método invoca al método public void deleteEstadosproduccion(int idBorrar)
//definido en el EstadosproduccionManager
 public void serviceDeleteEstadosproduccion(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 int idBorrar=-1;
	 idBorrar=WebUtils.getintParam(request, "borrarId");
	 if (idBorrar!=-1)
 		 if (EstadosproduccionManager.borraEstadosproduccion(idBorrar))
			 WebUtils.writeXmlResponse(response,XmlUtils.buildXmlOKResponse("ISO-8859-1"));
		 else
			 WebUtils.writeXmlResponse(response,XmlUtils.buildXmlNotOKResponse("ISO-8859-1"));			 
 }


// Funciones para las ordenaciones y filtrados de información

 private Criteria ordenacion(Criteria c,String CampoOrdenacion,String OrdenOrdenacion) 
 { 
 	if((OrdenOrdenacion != null )&& (OrdenOrdenacion.compareTo("ASC")==0))
 		if ((CampoOrdenacion != null))
 		{
 			c.addAscendingOrderByColumn(CampoOrdenacion.toString());
 		}
 	if  ((OrdenOrdenacion != null) && (OrdenOrdenacion.compareTo("DESC")==0))
 		if ((CampoOrdenacion != null))
		{
 			c.addDescendingOrderByColumn(CampoOrdenacion.toString());
 		}
 	return c;
 }

private Criteria filtro(Criteria c,int filtro) 
{ 
	String cadena = null;
	 switch (filtro)
	 {
	 case 1:
		  //Caso uno de Filtrado
		  //c.add(Campo,valor);
		  break;
	 case 2:
		  //Caso dos de Filtrado
		  //c.add(Campo,valor);
		  break;
	 default:
		 //caso por defecto
		 break;
	 }
	return c;
}

 public StringBuffer replaceStringBuffer (StringBuffer strBA, String strOrigen, String strDestino) 
 {
	 return new StringBuffer(strBA.toString().replaceAll(strOrigen,strDestino));
 }

 private Criteria criteriaEstadosproduccionTableContent(HttpServletRequest request,Criteria c) throws IOException, ServletException
 {
 	String param = "";	 
	  String paramSortCol =  WebUtils.getStringParam(request, "sort_col");
	  String paramSortDir =  WebUtils.getStringParam(request, "sort_dir");
	  int paramFiltro =  WebUtils.getintParam(request, "filtro");
	  c = ordenacion(c,paramSortCol,paramSortDir);
	  c = filtro(c,paramFiltro);

 	  return c;
 } 
 
 public String getPathElementEstadosproduccion(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
	 Criteria c= new Criteria();
	 String strPath = "";
	 int claveId=-1;
	 int claveFkId=-1;	 
	 claveId=WebUtils.getintParam(request, "estadosproduccion.IDESTADOPRODUCCION");
	 if (claveId!=-1)
	 {
		c.add(EstadosproduccionPeer.IDESTADOPRODUCCION, claveId);
		EstadosproduccionGroupBean trgb = EstadosproduccionManager.getEstadosproduccions(c);							
		strPath = trgb.getEstadosproduccion(0).getPathEstadosproduccionParsed(request.getQueryString());
	 }
	 return "<path>" + strPath + "</path>";
 } 
 
 public String getPathTableContentEstadosproduccion(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
	 Criteria c= new Criteria();
	 String strPath = "";
	 int claveId=-1;	 
	 return "<path>" + strPath + "</path>";
 }  


public void  serviceEstadosproduccionTableContent(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
	 utf8RequestService(request);
	 int numElemPedidosBD = 40;
	 int gap = 0;//gap = viewedRows - numElemVisiblesUltPag	  
	 DinamicGridBean dgb = WebUtils.getDinamicGridBeanParam(request,numElemPedidosBD,gap); 
	 Criteria c =EstadosproduccionManager.buildSearchCriteria(dgb);
	 c =criteriaEstadosproduccionTableContent(request,c);	 
	 EstadosproduccionGroupBean cgb = EstadosproduccionManager.getEstadosproduccions(c);
	 dgb.setTotalSize(cgb.getTotalSize());
	  
	 String[] methodos= new String[] {
		EstadosproduccionHelper.DESCRIPCION_GET_METHOD_NAME+"EstadosproduccionParsed"
		,"getHijosProduccionesEstadosproduccion"
		,"getEditEstadosproduccion"
		,"getDeleteEstadosproduccion"
	};
	 
	 StringBuffer cadena=null;
	 cadena = AjaxUtils.buildXmlAjaxResponseTableContentFromListObj(cgb.getAlmacen(),methodos,EstadosproduccionHelper.IDESTADOPRODUCCION_GET_METHOD_NAME, dgb,"ISO-8859-1"); 
	 cadena.insert(cadena.indexOf("</ajax-response>"),"<response type='object' id='divPath'>" + getPathTableContentEstadosproduccion(request,response) + "</response>");
	 xmlResponseService(response,cadena); 
 }  

 public void serviceEstadosproduccionUlContent(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
	 String[] methodos= new String[] {
	 		"getULContentEstadosproduccionParsed"
			 };
	 String param =  WebUtils.getStringParam(request, "value");
	 if(param==null || param.length() <= 0)
		 param =  WebUtils.getStringParam(request, new ProduccionesHelper().getIdestadoproduccionName());
	 	 
	 EstadosproduccionGroupBean mgb = EstadosproduccionManager.getEstadosproduccions(EstadosproduccionManager.buildSearchCriteria(param));
	 simpleResponseService(response, AjaxUtils.buildAjaxULContentFromListObj(mgb.getAlmacen(),methodos, EstadosproduccionHelper.COMPLEX_ID_GET_METHOD,"Estadosproduccion"));
 } 



 public void serviceEstadosproduccionElement(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
  StringBuffer cadena=null;
  Criteria c= new Criteria();
  int claveId=-1;
  claveId=WebUtils.getintParam(request, "estadosproduccion.IDESTADOPRODUCCION");
  if (claveId!=-1)
  {
	  c.add(EstadosproduccionPeer.IDESTADOPRODUCCION, claveId);
  }
  c.addAscendingOrderByColumn(EstadosproduccionPeer.IDESTADOPRODUCCION);
  EstadosproduccionGroupBean trgb = EstadosproduccionManager.getEstadosproduccions(c);
  
  if (trgb.getTotalSize()!=0)
  {
	  String [] parametros={
		EstadosproduccionHelper.IDESTADOPRODUCCION_GET_METHOD_NAME
		,EstadosproduccionHelper.DESCRIPCION_GET_METHOD_NAME+"EstadosproduccionParsed"
	  };
	  cadena=trgb.buildXml(parametros,null,"ISO-8859-1");	
	  cadena.insert(cadena.indexOf("</result>"),getPathElementEstadosproduccion(request,response));  
  }
  xmlResponseService(response, cadena);
 } 
 

 protected StringBuffer updateIdestadoproduccionResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(EstadosproduccionManager.getEstadosproduccion(Integer.parseInt(a.get(0).toString())).getIdestadoproduccionEstadosproduccionParsed());
 }  
 

 protected StringBuffer updateDescripcionResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(EstadosproduccionManager.getEstadosproduccion(Integer.parseInt(a.get(0).toString())).getDescripcionEstadosproduccionParsed());
 }  
 
 

 public void serviceGetEstadosproduccionDetallePdf(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
	 String[] getMethodos= new String[] {
		EstadosproduccionHelper.IDESTADOPRODUCCION_GET_METHOD_NAME
		,EstadosproduccionHelper.DESCRIPCION_GET_METHOD_NAME+"EstadosproduccionParsed"
			 };
	  
	 
	 EstadosproduccionGroupBean tgb = new EstadosproduccionGroupBean();
	 try
	{
		tgb.setElemento(EstadosproduccionHelper.getEstadosproduccion(request));
	} catch (TorqueException e)
	{
		logger.severe(e.getMessage());
	}
	
	 byte[] content =  PdfUtils.getBytes(replaceStringBuffer(tgb.buildXml(getMethodos, null,"ISO-8859-1"),"n/a"," "), estadosproduccion_transformer,"ISO-8859-1");
	 response.addHeader("content-disposition","attachment;filename=Estadosproduccion.pdf");
	 response.setContentType("application/pdf");
	 response.setHeader("Cache-Control", "");//para que funcione en IE
	 response.setContentLength(content.length);
	 response.getOutputStream().write(content);
	 response.getOutputStream().flush();  
	 response.getOutputStream().close();
	
 }  

 public void serviceEstadosproduccionTableContentPdf(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
  	utf8RequestService(request);
  	Criteria c= new Criteria();
  	String paramQuery =  WebUtils.getStringParam(request, "query");
  	if ((paramQuery != null)&& (paramQuery.compareTo("")!=0) )
		c = EstadosproduccionManager.buildSearchCriteria(paramQuery);   
  	c =criteriaEstadosproduccionTableContent(request,c);	  
  	EstadosproduccionGroupBean tgb = EstadosproduccionManager.getEstadosproduccions(c);
  
  	String[] methodos= new String[] {	
		EstadosproduccionHelper.DESCRIPCION_GET_METHOD_NAME+"EstadosproduccionParsed"
			};
  
	 byte[] content =  PdfUtils.getBytes(replaceStringBuffer(tgb.buildXml(methodos, null,"ISO-8859-1"),"n/a"," "), estadosproduccions_transformer,"ISO-8859-1");
	 response.addHeader("content-disposition","attachment;filename=ListaEstadosproduccion.pdf");
	 response.setContentType("application/pdf");
	 response.setHeader("Cache-Control", "");//para que funcione en IE
	 response.setContentLength(content.length);
	 response.getOutputStream().write(content);
	 response.getOutputStream().flush();  
	 response.getOutputStream().close();
 }

}


