package net.idtoki.adimde.controller;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.ResourceBundle;
import java.util.logging.Logger;

import javax.servlet.ServletConfig;
import javax.servlet.ServletContext;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.xml.transform.Source;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.stream.StreamSource;

import org.apache.torque.TorqueException;
import org.apache.torque.util.Criteria;

import net.idtoki.adimde.manager.MaterialesManager;
import net.idtoki.adimde.group.MaterialesGroupBean;
import net.idtoki.adimde.helper.MaterialesHelper;
import net.idtoki.adimde.model.MaterialesPeer;
import net.idtoki.adimde.model.Materiales;

import net.idtoki.adimde.manager.UnidadesmedidaManager;
import net.idtoki.adimde.group.UnidadesmedidaGroupBean;
import net.idtoki.adimde.model.UnidadesmedidaPeer;
import net.idtoki.adimde.helper.UnidadesmedidaHelper;

import net.idtoki.adimde.helper.ComposicionesHelper;


import net.zylk.tools.ajax.AjaxUtils;
import net.zylk.tools.ajax.AjaxUtils.DinamicGridBean;
import net.zylk.tools.format.FormatUtils;
import net.zylk.tools.pdf.PdfUtils;
import net.zylk.tools.xml.XmlUtils;
import net.zylk.torque.TorqueUtils;
import net.zylk.web.WebUtils;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Oct 26 17:10:22 CEST 2006]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
 
 
public class MaterialesController
    extends net.idtoki.adimde.controller.BaseMaterialesController
{
 private static final Logger logger = Logger.getLogger("net.idtoki.adimde.controller.MaterialesController");
 private TransformerFactory tFactory = TransformerFactory.newInstance();
 private Transformer materiales_transformer = null;  
 private Transformer materialess_transformer = null; 

 public void init(ServletConfig config)
 {
	super.init();
	ResourceBundle resource = ResourceBundle.getBundle("net/idtoki/adimde/app/config/app-config");
	File materiales = new File(resource.getString("app.xsl.templates.dir")+"/PdfMateriales.xslt");
	Source xslSource = new StreamSource(materiales);
	File materialess = new File(resource.getString("app.xsl.templates.dir")+"/PdfListaMateriales.xslt");
	Source xslSourceT = new StreamSource(materialess); 	  
	try{
		materiales_transformer = tFactory.newTransformer(xslSource);
		materialess_transformer = tFactory.newTransformer(xslSourceT);			  
	}catch (Exception e){
	  e.printStackTrace();
	}
 }


//Función para la inserción/actualización de registros

public void serviceAddMateriales(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 //Con esto se consigue transformar el request a UTF
	 //para temas de acentos y otros caracteres
	 utf8RequestService(request);

	 //recojo los parametros del formulario y doy de alta un nuevo elmento
	 try
	 {
		 Materiales elMateriales = MaterialesHelper.createObj(request);
		 MaterialesGroupBean gbMateriales = new MaterialesGroupBean();
		 gbMateriales.setElemento(elMateriales);
		 gbMateriales.save();
	 }
	 catch(TorqueException te)
	 {
		 response.sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
	 }
 }


//Función para la eliminación de un registro
//este método invoca al método public void deleteMateriales(int idBorrar)
//definido en el MaterialesManager
 public void serviceDeleteMateriales(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 int idBorrar=-1;
	 idBorrar=WebUtils.getintParam(request, "borrarId");
	 if (idBorrar!=-1)
 		 if (MaterialesManager.borraMateriales(idBorrar))
			 WebUtils.writeXmlResponse(response,XmlUtils.buildXmlOKResponse("ISO-8859-1"));
		 else
			 WebUtils.writeXmlResponse(response,XmlUtils.buildXmlNotOKResponse("ISO-8859-1"));			 
 }


// Funciones para las ordenaciones y filtrados de información

 private Criteria ordenacion(Criteria c,String CampoOrdenacion,String OrdenOrdenacion) 
 { 
 	if((OrdenOrdenacion != null )&& (OrdenOrdenacion.compareTo("ASC")==0))
 		if ((CampoOrdenacion != null))
 		{
 			c.addAscendingOrderByColumn(CampoOrdenacion.toString());
 		}
 	if  ((OrdenOrdenacion != null) && (OrdenOrdenacion.compareTo("DESC")==0))
 		if ((CampoOrdenacion != null))
		{
 			c.addDescendingOrderByColumn(CampoOrdenacion.toString());
 		}
 	return c;
 }

private Criteria filtro(Criteria c,int filtro) 
{ 
	String cadena = null;
	 switch (filtro)
	 {
	 case 1:
		  //Caso uno de Filtrado
		  //c.add(Campo,valor);
		  break;
	 case 2:
		  //Caso dos de Filtrado
		  //c.add(Campo,valor);
		  break;
	 default:
		 //caso por defecto
		 break;
	 }
	return c;
}

 public StringBuffer replaceStringBuffer (StringBuffer strBA, String strOrigen, String strDestino) 
 {
	 return new StringBuffer(strBA.toString().replaceAll(strOrigen,strDestino));
 }

 private Criteria criteriaMaterialesTableContent(HttpServletRequest request,Criteria c) throws IOException, ServletException
 {
 	String param = "";	 
	 param =  WebUtils.getStringParam(request, new UnidadesmedidaHelper().getIdunidadmedidaName());
	 if(param != null)
		 TorqueUtils.addEqualCriteria(c,MaterialesPeer.IDUNIDADMEDIDA,param);
	  String paramSortCol =  WebUtils.getStringParam(request, "sort_col");
	  String paramSortDir =  WebUtils.getStringParam(request, "sort_dir");
	  int paramFiltro =  WebUtils.getintParam(request, "filtro");
	  c = ordenacion(c,paramSortCol,paramSortDir);
	  c = filtro(c,paramFiltro);

 	  return c;
 } 
 
 public String getPathElementMateriales(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
	 Criteria c= new Criteria();
	 String strPath = "";
	 int claveId=-1;
	 int claveFkId=-1;	 
	 claveId=WebUtils.getintParam(request, "materiales.IDMATERIAL");
	 if (claveId!=-1)
	 {
		c.add(MaterialesPeer.IDMATERIAL, claveId);
		MaterialesGroupBean trgb = MaterialesManager.getMaterialess(c);							
		strPath = trgb.getMateriales(0).getPathMaterialesParsed(request.getQueryString());
	 }
	 return "<path>" + strPath + "</path>";
 } 
 
 public String getPathTableContentMateriales(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
	 Criteria c= new Criteria();
	 String strPath = "";
	 int claveId=-1;	 
	 claveId=WebUtils.getintParam(request, "unidadesmedida.IDUNIDADMEDIDA");
	 if(claveId != -1){
		 strPath = UnidadesmedidaManager.getUnidadesmedida(claveId).getPathUnidadesmedidaParsed(request.getQueryString());
	 }		 	 
	 return "<path>" + strPath + "</path>";
 }  


public void  serviceMaterialesTableContent(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
	 utf8RequestService(request);
	 int numElemPedidosBD = 40;
	 int gap = 0;//gap = viewedRows - numElemVisiblesUltPag	  
	 DinamicGridBean dgb = WebUtils.getDinamicGridBeanParam(request,numElemPedidosBD,gap); 
	 Criteria c =MaterialesManager.buildSearchCriteria(dgb);
	 c =criteriaMaterialesTableContent(request,c);	 
	 MaterialesGroupBean cgb = MaterialesManager.getMaterialess(c);
	 dgb.setTotalSize(cgb.getTotalSize());
	  
	 String[] methodos= new String[] {
		MaterialesHelper.NOMBRE_GET_METHOD_NAME+"MaterialesParsed"
		,MaterialesHelper.IDUNIDADMEDIDA_GET_METHOD_NAME+"MaterialesParsed"
		,MaterialesHelper.COSTE_GET_METHOD_NAME+"MaterialesParsed"
		,"getHijosComposicionesMateriales"
		,"getEditMateriales"
		,"getDeleteMateriales"
	};
	 
	 StringBuffer cadena=null;
	 cadena = AjaxUtils.buildXmlAjaxResponseTableContentFromListObj(cgb.getAlmacen(),methodos,MaterialesHelper.IDMATERIAL_GET_METHOD_NAME, dgb,"ISO-8859-1"); 
	 cadena.insert(cadena.indexOf("</ajax-response>"),"<response type='object' id='divPath'>" + getPathTableContentMateriales(request,response) + "</response>");
	 xmlResponseService(response,cadena); 
 }  

 public void serviceMaterialesUlContent(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
	 String[] methodos= new String[] {
	 		"getULContentMaterialesParsed"
			 };
	 String param =  WebUtils.getStringParam(request, "value");
	 if(param==null || param.length() <= 0)
		 param =  WebUtils.getStringParam(request, new ComposicionesHelper().getIdmaterialName());
	 	 
	 MaterialesGroupBean mgb = MaterialesManager.getMaterialess(MaterialesManager.buildSearchCriteria(param));
	 simpleResponseService(response, AjaxUtils.buildAjaxULContentFromListObj(mgb.getAlmacen(),methodos, MaterialesHelper.COMPLEX_ID_GET_METHOD,"Materiales"));
 } 



 public void serviceMaterialesElement(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
  StringBuffer cadena=null;
  Criteria c= new Criteria();
  int claveId=-1;
  claveId=WebUtils.getintParam(request, "materiales.IDMATERIAL");
  if (claveId!=-1)
  {
	  c.add(MaterialesPeer.IDMATERIAL, claveId);
  }
  c.addAscendingOrderByColumn(MaterialesPeer.IDMATERIAL);
  MaterialesGroupBean trgb = MaterialesManager.getMaterialess(c);
  
  if (trgb.getTotalSize()!=0)
  {
	  String [] parametros={
		MaterialesHelper.IDMATERIAL_GET_METHOD_NAME
		,MaterialesHelper.NOMBRE_GET_METHOD_NAME+"MaterialesParsed"
		,MaterialesHelper.IDUNIDADMEDIDA_GET_METHOD_NAME+"MaterialesParsed"
		,MaterialesHelper.COSTE_GET_METHOD_NAME+"MaterialesParsed"
	  };
	  cadena=trgb.buildXml(parametros,null,"ISO-8859-1");	
	  cadena.insert(cadena.indexOf("</result>"),getPathElementMateriales(request,response));  
  }
  xmlResponseService(response, cadena);
 } 
 

 protected StringBuffer updateIdmaterialResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(MaterialesManager.getMateriales(Integer.parseInt(a.get(0).toString())).getIdmaterialMaterialesParsed());
 }  
 

 protected StringBuffer updateNombreResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(MaterialesManager.getMateriales(Integer.parseInt(a.get(0).toString())).getNombreMaterialesParsed());
 }  
 

 protected StringBuffer updateIdunidadmedidaResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(MaterialesManager.getMateriales(Integer.parseInt(a.get(0).toString())).getIdunidadmedidaMaterialesParsed());
 }  
 

 protected StringBuffer updateCosteResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(MaterialesManager.getMateriales(Integer.parseInt(a.get(0).toString())).getCosteMaterialesParsed());
 }  
 
 
 
 public void serviceMaterialesUnidadesmedida(HttpServletRequest request, HttpServletResponse response) throws IOException, TorqueException, ServletException
 {
  String cadena=null;
  Criteria c= new Criteria();
  int claveId=-1;
  claveId=WebUtils.getintParam(request, "unidadesmedida.IDUNIDADMEDIDA");
  if (claveId!=-1)
  {
	  c.add(UnidadesmedidaPeer.IDUNIDADMEDIDA, claveId);
  }
  c.addAscendingOrderByColumn(UnidadesmedidaPeer.IDUNIDADMEDIDA);
  UnidadesmedidaGroupBean trgb = UnidadesmedidaManager.getUnidadesmedidas(c);
  
  if (trgb.getTotalSize()!=0)
  {
	  cadena = "<?xml version=\"1.0\" encoding=\"ISO-8859-1\" ?>";
	  cadena = cadena + "<result><materiales.IDUNIDADMEDIDA>" + trgb.getUnidadesmedida(0).getULContentUnidadesmedidaParsed()  + "</materiales.IDUNIDADMEDIDA></result>";
  }
  
  xmlResponseService(response, new StringBuffer(cadena));
 }  
  			

 public void serviceGetMaterialesDetallePdf(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
	 String[] getMethodos= new String[] {
		MaterialesHelper.IDMATERIAL_GET_METHOD_NAME
		,MaterialesHelper.NOMBRE_GET_METHOD_NAME+"MaterialesParsed"
		,MaterialesHelper.IDUNIDADMEDIDA_GET_METHOD_NAME+"MaterialesParsed"
		,MaterialesHelper.COSTE_GET_METHOD_NAME+"MaterialesParsed"
			 };
	  
	 
	 MaterialesGroupBean tgb = new MaterialesGroupBean();
	 try
	{
		tgb.setElemento(MaterialesHelper.getMateriales(request));
	} catch (TorqueException e)
	{
		logger.severe(e.getMessage());
	}
	
	 byte[] content =  PdfUtils.getBytes(replaceStringBuffer(tgb.buildXml(getMethodos, null,"ISO-8859-1"),"n/a"," "), materiales_transformer,"ISO-8859-1");
	 response.addHeader("content-disposition","attachment;filename=Materiales.pdf");
	 response.setContentType("application/pdf");
	 response.setHeader("Cache-Control", "");//para que funcione en IE
	 response.setContentLength(content.length);
	 response.getOutputStream().write(content);
	 response.getOutputStream().flush();  
	 response.getOutputStream().close();
	
 }  

 public void serviceMaterialesTableContentPdf(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
  	utf8RequestService(request);
  	Criteria c= new Criteria();
  	String paramQuery =  WebUtils.getStringParam(request, "query");
  	if ((paramQuery != null)&& (paramQuery.compareTo("")!=0) )
		c = MaterialesManager.buildSearchCriteria(paramQuery);   
  	c =criteriaMaterialesTableContent(request,c);	  
  	MaterialesGroupBean tgb = MaterialesManager.getMaterialess(c);
  
  	String[] methodos= new String[] {	
		MaterialesHelper.NOMBRE_GET_METHOD_NAME+"MaterialesParsed"
		,MaterialesHelper.IDUNIDADMEDIDA_GET_METHOD_NAME+"MaterialesParsed"
		,MaterialesHelper.COSTE_GET_METHOD_NAME+"MaterialesParsed"
			};
  
	 byte[] content =  PdfUtils.getBytes(replaceStringBuffer(tgb.buildXml(methodos, null,"ISO-8859-1"),"n/a"," "), materialess_transformer,"ISO-8859-1");
	 response.addHeader("content-disposition","attachment;filename=ListaMateriales.pdf");
	 response.setContentType("application/pdf");
	 response.setHeader("Cache-Control", "");//para que funcione en IE
	 response.setContentLength(content.length);
	 response.getOutputStream().write(content);
	 response.getOutputStream().flush();  
	 response.getOutputStream().close();
 }

}


