package net.idtoki.adimde.controller;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.ResourceBundle;
import java.util.logging.Logger;

import javax.servlet.ServletConfig;
import javax.servlet.ServletContext;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.xml.transform.Source;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.stream.StreamSource;

import org.apache.torque.TorqueException;
import org.apache.torque.util.Criteria;

import net.idtoki.adimde.manager.PartesManager;
import net.idtoki.adimde.group.PartesGroupBean;
import net.idtoki.adimde.helper.PartesHelper;
import net.idtoki.adimde.model.PartesPeer;
import net.idtoki.adimde.model.Partes;

import net.idtoki.adimde.manager.ProductosManager;
import net.idtoki.adimde.group.ProductosGroupBean;
import net.idtoki.adimde.model.ProductosPeer;
import net.idtoki.adimde.helper.ProductosHelper;
import net.idtoki.adimde.manager.OperariosManager;
import net.idtoki.adimde.group.OperariosGroupBean;
import net.idtoki.adimde.model.OperariosPeer;
import net.idtoki.adimde.helper.OperariosHelper;
import net.idtoki.adimde.manager.TurnosManager;
import net.idtoki.adimde.group.TurnosGroupBean;
import net.idtoki.adimde.model.TurnosPeer;
import net.idtoki.adimde.helper.TurnosHelper;



import net.zylk.tools.ajax.AjaxUtils;
import net.zylk.tools.ajax.AjaxUtils.DinamicGridBean;
import net.zylk.tools.format.FormatUtils;
import net.zylk.tools.pdf.PdfUtils;
import net.zylk.tools.xml.XmlUtils;
import net.zylk.torque.TorqueUtils;
import net.zylk.web.WebUtils;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Oct 02 10:34:00 CEST 2006]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
 
 
public class PartesController
    extends net.idtoki.adimde.controller.BasePartesController
{
 private static final Logger logger = Logger.getLogger("net.idtoki.adimde.controller.PartesController");
 private TransformerFactory tFactory = TransformerFactory.newInstance();
 private Transformer partes_transformer = null;  
 private Transformer partess_transformer = null; 

 public void init(ServletConfig config)
 {
	super.init();
	ResourceBundle resource = ResourceBundle.getBundle("net/idtoki/adimde/app/config/app-config");
	File partes = new File(resource.getString("app.xsl.templates.dir")+"/PdfPartes.xslt");
	Source xslSource = new StreamSource(partes);
	File partess = new File(resource.getString("app.xsl.templates.dir")+"/PdfListaPartes.xslt");
	Source xslSourceT = new StreamSource(partess); 	  
	try{
		partes_transformer = tFactory.newTransformer(xslSource);
		partess_transformer = tFactory.newTransformer(xslSourceT);			  
	}catch (Exception e){
	  e.printStackTrace();
	}
 }


//Función para la inserción/actualización de registros

public void serviceAddPartes(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 //Con esto se consigue transformar el request a UTF
	 //para temas de acentos y otros caracteres
	 utf8RequestService(request);

	 //recojo los parametros del formulario y doy de alta un nuevo elmento
	 try
	 {
		 Partes elPartes = PartesHelper.createObj(request);
		 PartesGroupBean gbPartes = new PartesGroupBean();
		 elPartes.setFecha(FormatUtils.ddmmaaaa2aaaammdd(elPartes.getFecha(),"-",""));
		 gbPartes.setElemento(elPartes);
		 gbPartes.save();
	 }
	 catch(TorqueException te)
	 {
		 response.sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
	 }
 }


//Función para la eliminación de un registro
//este método invoca al método public void deletePartes(int idBorrar)
//definido en el PartesManager
 public void serviceDeletePartes(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 int idBorrar=-1;
	 idBorrar=WebUtils.getintParam(request, "borrarId");
	 if (idBorrar!=-1)
 		 if (PartesManager.borraPartes(idBorrar))
			 WebUtils.writeXmlResponse(response,XmlUtils.buildXmlOKResponse("ISO-8859-1"));
		 else
			 WebUtils.writeXmlResponse(response,XmlUtils.buildXmlNotOKResponse("ISO-8859-1"));			 
 }


// Funciones para las ordenaciones y filtrados de información

 private Criteria ordenacion(Criteria c,String CampoOrdenacion,String OrdenOrdenacion) 
 { 
 	if((OrdenOrdenacion != null )&& (OrdenOrdenacion.compareTo("ASC")==0))
 		if ((CampoOrdenacion != null))
 		{
 			c.addAscendingOrderByColumn(CampoOrdenacion.toString());
 		}
 	if  ((OrdenOrdenacion != null) && (OrdenOrdenacion.compareTo("DESC")==0))
 		if ((CampoOrdenacion != null))
		{
 			c.addDescendingOrderByColumn(CampoOrdenacion.toString());
 		}
 	return c;
 }

private Criteria filtro(Criteria c,int filtro) 
{ 
	String cadena = null;
	 switch (filtro)
	 {
	 case 1:
		  //Caso uno de Filtrado
		  //c.add(Campo,valor);
		  break;
	 case 2:
		  //Caso dos de Filtrado
		  //c.add(Campo,valor);
		  break;
	 default:
		 //caso por defecto
		 break;
	 }
	return c;
}

 public StringBuffer replaceStringBuffer (StringBuffer strBA, String strOrigen, String strDestino) 
 {
	 return new StringBuffer(strBA.toString().replaceAll(strOrigen,strDestino));
 }

 private Criteria criteriaPartesTableContent(HttpServletRequest request,Criteria c) throws IOException, ServletException
 {
 	String param = "";	 
	 param =  WebUtils.getStringParam(request, new ProductosHelper().getIdproductoName());
	 if(param != null)
		 TorqueUtils.addEqualCriteria(c,PartesPeer.IDPRODUCTO,param);
	 param =  WebUtils.getStringParam(request, new OperariosHelper().getIdoperarioName());
	 if(param != null)
		 TorqueUtils.addEqualCriteria(c,PartesPeer.IDOPERARIO,param);
	 param =  WebUtils.getStringParam(request, new TurnosHelper().getIdturnoName());
	 if(param != null)
		 TorqueUtils.addEqualCriteria(c,PartesPeer.IDTURNO,param);
	  String paramSortCol =  WebUtils.getStringParam(request, "sort_col");
	  String paramSortDir =  WebUtils.getStringParam(request, "sort_dir");
	  int paramFiltro =  WebUtils.getintParam(request, "filtro");
	  c = ordenacion(c,paramSortCol,paramSortDir);
	  c = filtro(c,paramFiltro);

 	  return c;
 } 
 
 public String getPathElementPartes(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
	 Criteria c= new Criteria();
	 String strPath = "";
	 int claveId=-1;
	 int claveFkId=-1;	 
	 claveId=WebUtils.getintParam(request, "partes.IDPARTE");
	 if (claveId!=-1)
	 {
		c.add(PartesPeer.IDPARTE, claveId);
		PartesGroupBean trgb = PartesManager.getPartess(c);							
		strPath = trgb.getPartes(0).getPathPartesParsed(request.getQueryString());
	 }
	 return "<path>" + strPath + "</path>";
 } 
 
 public String getPathTableContentPartes(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
	 Criteria c= new Criteria();
	 String strPath = "";
	 int claveId=-1;	 
	 claveId=WebUtils.getintParam(request, "productos.IDPRODUCTO");
	 if(claveId != -1){
		 strPath = ProductosManager.getProductos(claveId).getPathProductosParsed(request.getQueryString());
	 }		 	 
	 claveId=WebUtils.getintParam(request, "operarios.IDOPERARIO");
	 if(claveId != -1){
		 strPath = OperariosManager.getOperarios(claveId).getPathOperariosParsed(request.getQueryString());
	 }		 	 
	 claveId=WebUtils.getintParam(request, "turnos.IDTURNO");
	 if(claveId != -1){
		 strPath = TurnosManager.getTurnos(claveId).getPathTurnosParsed(request.getQueryString());
	 }		 	 
	 return "<path>" + strPath + "</path>";
 }  


public void  servicePartesTableContent(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
	 utf8RequestService(request);
	 int numElemPedidosBD = 40;
	 int gap = 0;//gap = viewedRows - numElemVisiblesUltPag	  
	 DinamicGridBean dgb = WebUtils.getDinamicGridBeanParam(request,numElemPedidosBD,gap); 
	 Criteria c =PartesManager.buildSearchCriteria(dgb);
	 c =criteriaPartesTableContent(request,c);	 
	 PartesGroupBean cgb = PartesManager.getPartess(c);
	 dgb.setTotalSize(cgb.getTotalSize());
	  
	 String[] methodos= new String[] {
		PartesHelper.IDPRODUCTO_GET_METHOD_NAME+"PartesParsed"
		,PartesHelper.IDOPERARIO_GET_METHOD_NAME+"PartesParsed"
		,PartesHelper.IDTURNO_GET_METHOD_NAME+"PartesParsed"
		,PartesHelper.FECHA_GET_METHOD_NAME+"PartesParsed"
		//,PartesHelper.DESCRIPCION_GET_METHOD_NAME+"PartesParsed"
		//,PartesHelper.OBSERVACIONES_GET_METHOD_NAME+"PartesParsed"
		//,PartesHelper.HORAS_GET_METHOD_NAME+"PartesParsed"
		//,PartesHelper.UNIDADES_GET_METHOD_NAME+"PartesParsed"
		,"getEditPartes"
		,"getDeletePartes"
	};
	 
	 StringBuffer cadena=null;
	 cadena = AjaxUtils.buildXmlAjaxResponseTableContentFromListObj(cgb.getAlmacen(),methodos,PartesHelper.IDPARTE_GET_METHOD_NAME, dgb,"ISO-8859-1"); 
	 cadena.insert(cadena.indexOf("</ajax-response>"),"<response type='object' id='divPath'>" + getPathTableContentPartes(request,response) + "</response>");
	 xmlResponseService(response,cadena); 
 }  

 public void servicePartesUlContent(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
	 String[] methodos= new String[] {
	 		"getULContentPartesParsed"
			 };
	 String param =  WebUtils.getStringParam(request, "value");
	 	 
	 PartesGroupBean mgb = PartesManager.getPartess(PartesManager.buildSearchCriteria(param));
	 simpleResponseService(response, AjaxUtils.buildAjaxULContentFromListObj(mgb.getAlmacen(),methodos, PartesHelper.COMPLEX_ID_GET_METHOD,"Partes"));
 } 



 public void servicePartesElement(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
  StringBuffer cadena=null;
  Criteria c= new Criteria();
  int claveId=-1;
  claveId=WebUtils.getintParam(request, "partes.IDPARTE");
  if (claveId!=-1)
  {
	  c.add(PartesPeer.IDPARTE, claveId);
  }
  c.addAscendingOrderByColumn(PartesPeer.IDPARTE);
  PartesGroupBean trgb = PartesManager.getPartess(c);
  
  if (trgb.getTotalSize()!=0)
  {
	  String [] parametros={
		PartesHelper.IDPARTE_GET_METHOD_NAME
		,PartesHelper.IDPRODUCTO_GET_METHOD_NAME+"PartesParsed"
		,PartesHelper.IDOPERARIO_GET_METHOD_NAME+"PartesParsed"
		,PartesHelper.IDTURNO_GET_METHOD_NAME+"PartesParsed"
		,PartesHelper.FECHA_GET_METHOD_NAME+"PartesParsed"
		,PartesHelper.DESCRIPCION_GET_METHOD_NAME+"PartesParsed"
		,PartesHelper.OBSERVACIONES_GET_METHOD_NAME+"PartesParsed"
		,PartesHelper.HORAS_GET_METHOD_NAME+"PartesParsed"
		,PartesHelper.UNIDADES_GET_METHOD_NAME+"PartesParsed"
		,"getManoObraPartesParsed"
	  };
	  cadena=trgb.buildXml(parametros,null,"ISO-8859-1");	
	  cadena.insert(cadena.indexOf("</result>"),getPathElementPartes(request,response));  
  }
  xmlResponseService(response, cadena);
 } 
 

 protected StringBuffer updateIdparteResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(PartesManager.getPartes(Integer.parseInt(a.get(0).toString())).getIdpartePartesParsed());
 }  
 

 protected StringBuffer updateIdproductoResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(PartesManager.getPartes(Integer.parseInt(a.get(0).toString())).getIdproductoPartesParsed());
 }  
 

 protected StringBuffer updateIdoperarioResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(PartesManager.getPartes(Integer.parseInt(a.get(0).toString())).getIdoperarioPartesParsed());
 }  
 

 protected StringBuffer updateIdturnoResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(PartesManager.getPartes(Integer.parseInt(a.get(0).toString())).getIdturnoPartesParsed());
 }  
 

 protected StringBuffer updateFechaResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(PartesManager.getPartes(Integer.parseInt(a.get(0).toString())).getFechaPartesParsed());
 }  
 

 protected StringBuffer updateDescripcionResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(PartesManager.getPartes(Integer.parseInt(a.get(0).toString())).getDescripcionPartesParsed());
 }  
 

 protected StringBuffer updateObservacionesResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(PartesManager.getPartes(Integer.parseInt(a.get(0).toString())).getObservacionesPartesParsed());
 }  
 

 protected StringBuffer updateHorasResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(PartesManager.getPartes(Integer.parseInt(a.get(0).toString())).getHorasPartesParsed());
 }  
 

 protected StringBuffer updateUnidadesResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(PartesManager.getPartes(Integer.parseInt(a.get(0).toString())).getUnidadesPartesParsed());
 }  
 
 
 
 public void servicePartesProductos(HttpServletRequest request, HttpServletResponse response) throws IOException, TorqueException, ServletException
 {
  String cadena=null;
  Criteria c= new Criteria();
  int claveId=-1;
  claveId=WebUtils.getintParam(request, "productos.IDPRODUCTO");
  if (claveId!=-1)
  {
	  c.add(ProductosPeer.IDPRODUCTO, claveId);
  }
  c.addAscendingOrderByColumn(ProductosPeer.IDPRODUCTO);
  ProductosGroupBean trgb = ProductosManager.getProductoss(c);
  
  if (trgb.getTotalSize()!=0)
  {
	  cadena = "<?xml version=\"1.0\" encoding=\"ISO-8859-1\" ?>";
	  cadena = cadena + "<result><partes.IDPRODUCTO>" + trgb.getProductos(0).getULContentProductosParsed()  + "</partes.IDPRODUCTO></result>";
  }
  
  xmlResponseService(response, new StringBuffer(cadena));
 }  
  			
 
 public void servicePartesOperarios(HttpServletRequest request, HttpServletResponse response) throws IOException, TorqueException, ServletException
 {
  String cadena=null;
  Criteria c= new Criteria();
  int claveId=-1;
  claveId=WebUtils.getintParam(request, "operarios.IDOPERARIO");
  if (claveId!=-1)
  {
	  c.add(OperariosPeer.IDOPERARIO, claveId);
  }
  c.addAscendingOrderByColumn(OperariosPeer.IDOPERARIO);
  OperariosGroupBean trgb = OperariosManager.getOperarioss(c);
  
  if (trgb.getTotalSize()!=0)
  {
	  cadena = "<?xml version=\"1.0\" encoding=\"ISO-8859-1\" ?>";
	  cadena = cadena + "<result><partes.IDOPERARIO>" + trgb.getOperarios(0).getULContentOperariosParsed()  + "</partes.IDOPERARIO></result>";
  }
  
  xmlResponseService(response, new StringBuffer(cadena));
 }  
  			
 
 public void servicePartesTurnos(HttpServletRequest request, HttpServletResponse response) throws IOException, TorqueException, ServletException
 {
  String cadena=null;
  Criteria c= new Criteria();
  int claveId=-1;
  claveId=WebUtils.getintParam(request, "turnos.IDTURNO");
  if (claveId!=-1)
  {
	  c.add(TurnosPeer.IDTURNO, claveId);
  }
  c.addAscendingOrderByColumn(TurnosPeer.IDTURNO);
  TurnosGroupBean trgb = TurnosManager.getTurnoss(c);
  
  if (trgb.getTotalSize()!=0)
  {
	  cadena = "<?xml version=\"1.0\" encoding=\"ISO-8859-1\" ?>";
	  cadena = cadena + "<result><partes.IDTURNO>" + trgb.getTurnos(0).getULContentTurnosParsed()  + "</partes.IDTURNO></result>";
  }
  
  xmlResponseService(response, new StringBuffer(cadena));
 }  
  			

 public void serviceGetPartesDetallePdf(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
	 String[] getMethodos= new String[] {
		PartesHelper.IDPARTE_GET_METHOD_NAME
		,PartesHelper.IDPRODUCTO_GET_METHOD_NAME+"PartesParsed"
		,PartesHelper.IDOPERARIO_GET_METHOD_NAME+"PartesParsed"
		,PartesHelper.IDTURNO_GET_METHOD_NAME+"PartesParsed"
		,PartesHelper.FECHA_GET_METHOD_NAME+"PartesParsed"
		,PartesHelper.DESCRIPCION_GET_METHOD_NAME+"PartesParsed"
		,PartesHelper.OBSERVACIONES_GET_METHOD_NAME+"PartesParsed"
		,PartesHelper.HORAS_GET_METHOD_NAME+"PartesParsed"
		,PartesHelper.UNIDADES_GET_METHOD_NAME+"PartesParsed"
			 };
	  
	 
	 PartesGroupBean tgb = new PartesGroupBean();
	 try
	{
		tgb.setElemento(PartesHelper.getPartes(request));
	} catch (TorqueException e)
	{
		logger.severe(e.getMessage());
	}
	
	 byte[] content =  PdfUtils.getBytes(replaceStringBuffer(tgb.buildXml(getMethodos, null,"ISO-8859-1"),"n/a"," "), partes_transformer,"ISO-8859-1");
	 response.addHeader("content-disposition","attachment;filename=Partes.pdf");
	 response.setContentType("application/pdf");
	 response.setHeader("Cache-Control", "");//para que funcione en IE
	 response.setContentLength(content.length);
	 response.getOutputStream().write(content);
	 response.getOutputStream().flush();  
	 response.getOutputStream().close();
	
 }  

 public void servicePartesTableContentPdf(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
  	utf8RequestService(request);
  	Criteria c= new Criteria();
  	String paramQuery =  WebUtils.getStringParam(request, "query");
  	if ((paramQuery != null)&& (paramQuery.compareTo("")!=0) )
		c = PartesManager.buildSearchCriteria(paramQuery);   
  	c =criteriaPartesTableContent(request,c);	  
  	PartesGroupBean tgb = PartesManager.getPartess(c);
  
  	String[] methodos= new String[] {	
		PartesHelper.IDPRODUCTO_GET_METHOD_NAME+"PartesParsed"
		,PartesHelper.IDOPERARIO_GET_METHOD_NAME+"PartesParsed"
		,PartesHelper.IDTURNO_GET_METHOD_NAME+"PartesParsed"
		,PartesHelper.FECHA_GET_METHOD_NAME+"PartesParsed"
		,PartesHelper.DESCRIPCION_GET_METHOD_NAME+"PartesParsed"
		,PartesHelper.OBSERVACIONES_GET_METHOD_NAME+"PartesParsed"
		,PartesHelper.HORAS_GET_METHOD_NAME+"PartesParsed"
		,PartesHelper.UNIDADES_GET_METHOD_NAME+"PartesParsed"
			};
  
	 byte[] content =  PdfUtils.getBytes(replaceStringBuffer(tgb.buildXml(methodos, null,"ISO-8859-1"),"n/a"," "), partess_transformer,"ISO-8859-1");
	 response.addHeader("content-disposition","attachment;filename=ListaPartes.pdf");
	 response.setContentType("application/pdf");
	 response.setHeader("Cache-Control", "");//para que funcione en IE
	 response.setContentLength(content.length);
	 response.getOutputStream().write(content);
	 response.getOutputStream().flush();  
	 response.getOutputStream().close();
 }

}


