package net.idtoki.adimde.controller;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.ResourceBundle;
import java.util.logging.Logger;

import javax.servlet.ServletConfig;
import javax.servlet.ServletContext;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.xml.transform.Source;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.stream.StreamSource;

import org.apache.torque.TorqueException;
import org.apache.torque.util.Criteria;

import net.idtoki.adimde.manager.PerfilesManager;
import net.idtoki.adimde.group.PerfilesGroupBean;
import net.idtoki.adimde.helper.PerfilesHelper;
import net.idtoki.adimde.model.PerfilesPeer;
import net.idtoki.adimde.model.Perfiles;


import net.idtoki.adimde.helper.OperariosHelper;
import net.idtoki.adimde.helper.PerfilturnoHelper;


import net.zylk.tools.ajax.AjaxUtils;
import net.zylk.tools.ajax.AjaxUtils.DinamicGridBean;
import net.zylk.tools.format.FormatUtils;
import net.zylk.tools.pdf.PdfUtils;
import net.zylk.tools.xml.XmlUtils;
import net.zylk.torque.TorqueUtils;
import net.zylk.web.WebUtils;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Oct 02 10:34:00 CEST 2006]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
 
 
public class PerfilesController
    extends net.idtoki.adimde.controller.BasePerfilesController
{
 private static final Logger logger = Logger.getLogger("net.idtoki.adimde.controller.PerfilesController");
 private TransformerFactory tFactory = TransformerFactory.newInstance();
 private Transformer perfiles_transformer = null;  
 private Transformer perfiless_transformer = null; 

 public void init(ServletConfig config)
 {
	super.init();
	ResourceBundle resource = ResourceBundle.getBundle("net/idtoki/adimde/app/config/app-config");
	File perfiles = new File(resource.getString("app.xsl.templates.dir")+"/PdfPerfiles.xslt");
	Source xslSource = new StreamSource(perfiles);
	File perfiless = new File(resource.getString("app.xsl.templates.dir")+"/PdfListaPerfiles.xslt");
	Source xslSourceT = new StreamSource(perfiless); 	  
	try{
		perfiles_transformer = tFactory.newTransformer(xslSource);
		perfiless_transformer = tFactory.newTransformer(xslSourceT);			  
	}catch (Exception e){
	  e.printStackTrace();
	}
 }


//Función para la inserción/actualización de registros

public void serviceAddPerfiles(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 //Con esto se consigue transformar el request a UTF
	 //para temas de acentos y otros caracteres
	 utf8RequestService(request);

	 //recojo los parametros del formulario y doy de alta un nuevo elmento
	 try
	 {
		 Perfiles elPerfiles = PerfilesHelper.createObj(request);
		 PerfilesGroupBean gbPerfiles = new PerfilesGroupBean();
		 gbPerfiles.setElemento(elPerfiles);
		 gbPerfiles.save();
	 }
	 catch(TorqueException te)
	 {
		 response.sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
	 }
 }


//Función para la eliminación de un registro
//este método invoca al método public void deletePerfiles(int idBorrar)
//definido en el PerfilesManager
 public void serviceDeletePerfiles(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 int idBorrar=-1;
	 idBorrar=WebUtils.getintParam(request, "borrarId");
	 if (idBorrar!=-1)
 		 if (PerfilesManager.borraPerfiles(idBorrar))
			 WebUtils.writeXmlResponse(response,XmlUtils.buildXmlOKResponse("ISO-8859-1"));
		 else
			 WebUtils.writeXmlResponse(response,XmlUtils.buildXmlNotOKResponse("ISO-8859-1"));			 
 }


// Funciones para las ordenaciones y filtrados de información

 private Criteria ordenacion(Criteria c,String CampoOrdenacion,String OrdenOrdenacion) 
 { 
 	if((OrdenOrdenacion != null )&& (OrdenOrdenacion.compareTo("ASC")==0))
 		if ((CampoOrdenacion != null))
 		{
 			c.addAscendingOrderByColumn(CampoOrdenacion.toString());
 		}
 	if  ((OrdenOrdenacion != null) && (OrdenOrdenacion.compareTo("DESC")==0))
 		if ((CampoOrdenacion != null))
		{
 			c.addDescendingOrderByColumn(CampoOrdenacion.toString());
 		}
 	return c;
 }

private Criteria filtro(Criteria c,int filtro) 
{ 
	String cadena = null;
	 switch (filtro)
	 {
	 case 1:
		  //Caso uno de Filtrado
		  //c.add(Campo,valor);
		  break;
	 case 2:
		  //Caso dos de Filtrado
		  //c.add(Campo,valor);
		  break;
	 default:
		 //caso por defecto
		 break;
	 }
	return c;
}

 public StringBuffer replaceStringBuffer (StringBuffer strBA, String strOrigen, String strDestino) 
 {
	 return new StringBuffer(strBA.toString().replaceAll(strOrigen,strDestino));
 }

 private Criteria criteriaPerfilesTableContent(HttpServletRequest request,Criteria c) throws IOException, ServletException
 {
 	String param = "";	 
	  String paramSortCol =  WebUtils.getStringParam(request, "sort_col");
	  String paramSortDir =  WebUtils.getStringParam(request, "sort_dir");
	  int paramFiltro =  WebUtils.getintParam(request, "filtro");
	  c = ordenacion(c,paramSortCol,paramSortDir);
	  c = filtro(c,paramFiltro);

 	  return c;
 } 
 
 public String getPathElementPerfiles(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
	 Criteria c= new Criteria();
	 String strPath = "";
	 int claveId=-1;
	 int claveFkId=-1;	 
	 claveId=WebUtils.getintParam(request, "perfiles.IDPERFIL");
	 if (claveId!=-1)
	 {
		c.add(PerfilesPeer.IDPERFIL, claveId);
		PerfilesGroupBean trgb = PerfilesManager.getPerfiless(c);							
		strPath = trgb.getPerfiles(0).getPathPerfilesParsed(request.getQueryString());
	 }
	 return "<path>" + strPath + "</path>";
 } 
 
 public String getPathTableContentPerfiles(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
	 Criteria c= new Criteria();
	 String strPath = "";
	 int claveId=-1;	 
	 return "<path>" + strPath + "</path>";
 }  


public void  servicePerfilesTableContent(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
	 utf8RequestService(request);
	 int numElemPedidosBD = 40;
	 int gap = 0;//gap = viewedRows - numElemVisiblesUltPag	  
	 DinamicGridBean dgb = WebUtils.getDinamicGridBeanParam(request,numElemPedidosBD,gap); 
	 Criteria c =PerfilesManager.buildSearchCriteria(dgb);
	 c =criteriaPerfilesTableContent(request,c);	 
	 PerfilesGroupBean cgb = PerfilesManager.getPerfiless(c);
	 dgb.setTotalSize(cgb.getTotalSize());
	  
	 String[] methodos= new String[] {
		PerfilesHelper.DESCRIPCION_GET_METHOD_NAME+"PerfilesParsed"
		,"getHijosOperariosPerfiles"
		,"getHijosPerfilturnoPerfiles"
		,"getEditPerfiles"
		,"getDeletePerfiles"
	};
	 
	 StringBuffer cadena=null;
	 cadena = AjaxUtils.buildXmlAjaxResponseTableContentFromListObj(cgb.getAlmacen(),methodos,PerfilesHelper.IDPERFIL_GET_METHOD_NAME, dgb,"ISO-8859-1"); 
	 cadena.insert(cadena.indexOf("</ajax-response>"),"<response type='object' id='divPath'>" + getPathTableContentPerfiles(request,response) + "</response>");
	 xmlResponseService(response,cadena); 
 }  

 public void servicePerfilesUlContent(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
	 String[] methodos= new String[] {
	 		"getULContentPerfilesParsed"
			 };
	 String param =  WebUtils.getStringParam(request, "value");
	 if(param==null || param.length() <= 0)
		 param =  WebUtils.getStringParam(request, new OperariosHelper().getIdperfilName());
	 if(param==null || param.length() <= 0)
		 param =  WebUtils.getStringParam(request, new PerfilturnoHelper().getIdperfilName());
	 	 
	 PerfilesGroupBean mgb = PerfilesManager.getPerfiless(PerfilesManager.buildSearchCriteria(param));
	 simpleResponseService(response, AjaxUtils.buildAjaxULContentFromListObj(mgb.getAlmacen(),methodos, PerfilesHelper.COMPLEX_ID_GET_METHOD,"Perfiles"));
 } 



 public void servicePerfilesElement(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
  StringBuffer cadena=null;
  Criteria c= new Criteria();
  int claveId=-1;
  claveId=WebUtils.getintParam(request, "perfiles.IDPERFIL");
  if (claveId!=-1)
  {
	  c.add(PerfilesPeer.IDPERFIL, claveId);
  }
  c.addAscendingOrderByColumn(PerfilesPeer.IDPERFIL);
  PerfilesGroupBean trgb = PerfilesManager.getPerfiless(c);
  
  if (trgb.getTotalSize()!=0)
  {
	  String [] parametros={
		PerfilesHelper.IDPERFIL_GET_METHOD_NAME
		,PerfilesHelper.DESCRIPCION_GET_METHOD_NAME+"PerfilesParsed"
	  };
	  cadena=trgb.buildXml(parametros,null,"ISO-8859-1");	
	  cadena.insert(cadena.indexOf("</result>"),getPathElementPerfiles(request,response));  
  }
  xmlResponseService(response, cadena);
 } 
 

 protected StringBuffer updateIdperfilResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(PerfilesManager.getPerfiles(Integer.parseInt(a.get(0).toString())).getIdperfilPerfilesParsed());
 }  
 

 protected StringBuffer updateDescripcionResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(PerfilesManager.getPerfiles(Integer.parseInt(a.get(0).toString())).getDescripcionPerfilesParsed());
 }  
 
 

 public void serviceGetPerfilesDetallePdf(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
	 String[] getMethodos= new String[] {
		PerfilesHelper.IDPERFIL_GET_METHOD_NAME
		,PerfilesHelper.DESCRIPCION_GET_METHOD_NAME+"PerfilesParsed"
			 };
	  
	 
	 PerfilesGroupBean tgb = new PerfilesGroupBean();
	 try
	{
		tgb.setElemento(PerfilesHelper.getPerfiles(request));
	} catch (TorqueException e)
	{
		logger.severe(e.getMessage());
	}
	
	 byte[] content =  PdfUtils.getBytes(replaceStringBuffer(tgb.buildXml(getMethodos, null,"ISO-8859-1"),"n/a"," "), perfiles_transformer,"ISO-8859-1");
	 response.addHeader("content-disposition","attachment;filename=Perfiles.pdf");
	 response.setContentType("application/pdf");
	 response.setHeader("Cache-Control", "");//para que funcione en IE
	 response.setContentLength(content.length);
	 response.getOutputStream().write(content);
	 response.getOutputStream().flush();  
	 response.getOutputStream().close();
	
 }  

 public void servicePerfilesTableContentPdf(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
  	utf8RequestService(request);
  	Criteria c= new Criteria();
  	String paramQuery =  WebUtils.getStringParam(request, "query");
  	if ((paramQuery != null)&& (paramQuery.compareTo("")!=0) )
		c = PerfilesManager.buildSearchCriteria(paramQuery);   
  	c =criteriaPerfilesTableContent(request,c);	  
  	PerfilesGroupBean tgb = PerfilesManager.getPerfiless(c);
  
  	String[] methodos= new String[] {	
		PerfilesHelper.DESCRIPCION_GET_METHOD_NAME+"PerfilesParsed"
			};
  
	 byte[] content =  PdfUtils.getBytes(replaceStringBuffer(tgb.buildXml(methodos, null,"ISO-8859-1"),"n/a"," "), perfiless_transformer,"ISO-8859-1");
	 response.addHeader("content-disposition","attachment;filename=ListaPerfiles.pdf");
	 response.setContentType("application/pdf");
	 response.setHeader("Cache-Control", "");//para que funcione en IE
	 response.setContentLength(content.length);
	 response.getOutputStream().write(content);
	 response.getOutputStream().flush();  
	 response.getOutputStream().close();
 }

}


