package net.idtoki.adimde.controller;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.ResourceBundle;
import java.util.logging.Logger;

import javax.servlet.ServletConfig;
import javax.servlet.ServletContext;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.xml.transform.Source;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.stream.StreamSource;

import org.apache.torque.TorqueException;
import org.apache.torque.util.Criteria;

import net.idtoki.adimde.manager.PerfilturnoManager;
import net.idtoki.adimde.group.PerfilturnoGroupBean;
import net.idtoki.adimde.helper.PerfilturnoHelper;
import net.idtoki.adimde.model.PerfilturnoPeer;
import net.idtoki.adimde.model.Perfilturno;

import net.idtoki.adimde.manager.PerfilesManager;
import net.idtoki.adimde.group.PerfilesGroupBean;
import net.idtoki.adimde.model.PerfilesPeer;
import net.idtoki.adimde.helper.PerfilesHelper;
import net.idtoki.adimde.manager.TurnosManager;
import net.idtoki.adimde.group.TurnosGroupBean;
import net.idtoki.adimde.model.TurnosPeer;
import net.idtoki.adimde.helper.TurnosHelper;



import net.zylk.tools.ajax.AjaxUtils;
import net.zylk.tools.ajax.AjaxUtils.DinamicGridBean;
import net.zylk.tools.format.FormatUtils;
import net.zylk.tools.pdf.PdfUtils;
import net.zylk.tools.xml.XmlUtils;
import net.zylk.torque.TorqueUtils;
import net.zylk.web.WebUtils;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Oct 02 10:34:00 CEST 2006]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
 
 
public class PerfilturnoController
    extends net.idtoki.adimde.controller.BasePerfilturnoController
{
 private static final Logger logger = Logger.getLogger("net.idtoki.adimde.controller.PerfilturnoController");
 private TransformerFactory tFactory = TransformerFactory.newInstance();
 private Transformer perfilturno_transformer = null;  
 private Transformer perfilturnos_transformer = null; 

 public void init(ServletConfig config)
 {
	super.init();
	ResourceBundle resource = ResourceBundle.getBundle("net/idtoki/adimde/app/config/app-config");
	File perfilturno = new File(resource.getString("app.xsl.templates.dir")+"/PdfPerfilturno.xslt");
	Source xslSource = new StreamSource(perfilturno);
	File perfilturnos = new File(resource.getString("app.xsl.templates.dir")+"/PdfListaPerfilturno.xslt");
	Source xslSourceT = new StreamSource(perfilturnos); 	  
	try{
		perfilturno_transformer = tFactory.newTransformer(xslSource);
		perfilturnos_transformer = tFactory.newTransformer(xslSourceT);			  
	}catch (Exception e){
	  e.printStackTrace();
	}
 }


//Función para la inserción/actualización de registros

public void serviceAddPerfilturno(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 //Con esto se consigue transformar el request a UTF
	 //para temas de acentos y otros caracteres
	 utf8RequestService(request);

	 //recojo los parametros del formulario y doy de alta un nuevo elmento
	 try
	 {
		 Perfilturno elPerfilturno = PerfilturnoHelper.createObj(request);
		 PerfilturnoGroupBean gbPerfilturno = new PerfilturnoGroupBean();
		 gbPerfilturno.setElemento(elPerfilturno);
		 gbPerfilturno.save();
	 }
	 catch(TorqueException te)
	 {
		 response.sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
	 }
 }


//Función para la eliminación de un registro
//este método invoca al método public void deletePerfilturno(int idBorrar)
//definido en el PerfilturnoManager
 public void serviceDeletePerfilturno(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 int idBorrar=-1;
	 idBorrar=WebUtils.getintParam(request, "borrarId");
	 if (idBorrar!=-1)
 		 if (PerfilturnoManager.borraPerfilturno(idBorrar))
			 WebUtils.writeXmlResponse(response,XmlUtils.buildXmlOKResponse("ISO-8859-1"));
		 else
			 WebUtils.writeXmlResponse(response,XmlUtils.buildXmlNotOKResponse("ISO-8859-1"));			 
 }


// Funciones para las ordenaciones y filtrados de información

 private Criteria ordenacion(Criteria c,String CampoOrdenacion,String OrdenOrdenacion) 
 { 
 	if((OrdenOrdenacion != null )&& (OrdenOrdenacion.compareTo("ASC")==0))
 		if ((CampoOrdenacion != null))
 		{
 			c.addAscendingOrderByColumn(CampoOrdenacion.toString());
 		}
 	if  ((OrdenOrdenacion != null) && (OrdenOrdenacion.compareTo("DESC")==0))
 		if ((CampoOrdenacion != null))
		{
 			c.addDescendingOrderByColumn(CampoOrdenacion.toString());
 		}
 	return c;
 }

private Criteria filtro(Criteria c,int filtro) 
{ 
	String cadena = null;
	 switch (filtro)
	 {
	 case 1:
		  //Caso uno de Filtrado
		  //c.add(Campo,valor);
		  break;
	 case 2:
		  //Caso dos de Filtrado
		  //c.add(Campo,valor);
		  break;
	 default:
		 //caso por defecto
		 break;
	 }
	return c;
}

 public StringBuffer replaceStringBuffer (StringBuffer strBA, String strOrigen, String strDestino) 
 {
	 return new StringBuffer(strBA.toString().replaceAll(strOrigen,strDestino));
 }

 private Criteria criteriaPerfilturnoTableContent(HttpServletRequest request,Criteria c) throws IOException, ServletException
 {
 	String param = "";	 
	 param =  WebUtils.getStringParam(request, new PerfilesHelper().getIdperfilName());
	 if(param != null)
		 TorqueUtils.addEqualCriteria(c,PerfilturnoPeer.IDPERFIL,param);
	 param =  WebUtils.getStringParam(request, new TurnosHelper().getIdturnoName());
	 if(param != null)
		 TorqueUtils.addEqualCriteria(c,PerfilturnoPeer.IDTURNO,param);
	  String paramSortCol =  WebUtils.getStringParam(request, "sort_col");
	  String paramSortDir =  WebUtils.getStringParam(request, "sort_dir");
	  int paramFiltro =  WebUtils.getintParam(request, "filtro");
	  c = ordenacion(c,paramSortCol,paramSortDir);
	  c = filtro(c,paramFiltro);

 	  return c;
 } 
 
 public String getPathElementPerfilturno(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
	 Criteria c= new Criteria();
	 String strPath = "";
	 int claveId=-1;
	 int claveFkId=-1;	 
	 claveId=WebUtils.getintParam(request, "perfilturno.IDTP");
	 if (claveId!=-1)
	 {
		c.add(PerfilturnoPeer.IDTP, claveId);
		PerfilturnoGroupBean trgb = PerfilturnoManager.getPerfilturnos(c);							
		strPath = trgb.getPerfilturno(0).getPathPerfilturnoParsed(request.getQueryString());
	 }
	 return "<path>" + strPath + "</path>";
 } 
 
 public String getPathTableContentPerfilturno(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
	 Criteria c= new Criteria();
	 String strPath = "";
	 int claveId=-1;	 
	 claveId=WebUtils.getintParam(request, "perfiles.IDPERFIL");
	 if(claveId != -1){
		 strPath = PerfilesManager.getPerfiles(claveId).getPathPerfilesParsed(request.getQueryString());
	 }		 	 
	 claveId=WebUtils.getintParam(request, "turnos.IDTURNO");
	 if(claveId != -1){
		 strPath = TurnosManager.getTurnos(claveId).getPathTurnosParsed(request.getQueryString());
	 }		 	 
	 return "<path>" + strPath + "</path>";
 }  


public void  servicePerfilturnoTableContent(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
	 utf8RequestService(request);
	 int numElemPedidosBD = 40;
	 int gap = 0;//gap = viewedRows - numElemVisiblesUltPag	  
	 DinamicGridBean dgb = WebUtils.getDinamicGridBeanParam(request,numElemPedidosBD,gap); 
	 Criteria c =PerfilturnoManager.buildSearchCriteria(dgb);
	 c =criteriaPerfilturnoTableContent(request,c);	 
	 PerfilturnoGroupBean cgb = PerfilturnoManager.getPerfilturnos(c);
	 dgb.setTotalSize(cgb.getTotalSize());
	  
	 String[] methodos= new String[] {
		PerfilturnoHelper.IDPERFIL_GET_METHOD_NAME+"PerfilturnoParsed"
		,PerfilturnoHelper.IDTURNO_GET_METHOD_NAME+"PerfilturnoParsed"
		,PerfilturnoHelper.VALORCOSTE_GET_METHOD_NAME+"PerfilturnoParsed"
		,"getEditPerfilturno"
		,"getDeletePerfilturno"
	};
	 
	 StringBuffer cadena=null;
	 cadena = AjaxUtils.buildXmlAjaxResponseTableContentFromListObj(cgb.getAlmacen(),methodos,PerfilturnoHelper.IDTP_GET_METHOD_NAME, dgb,"ISO-8859-1"); 
	 cadena.insert(cadena.indexOf("</ajax-response>"),"<response type='object' id='divPath'>" + getPathTableContentPerfilturno(request,response) + "</response>");
	 xmlResponseService(response,cadena); 
 }  

 public void servicePerfilturnoUlContent(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
	 String[] methodos= new String[] {
	 		"getULContentPerfilturnoParsed"
			 };
	 String param =  WebUtils.getStringParam(request, "value");
	 	 
	 PerfilturnoGroupBean mgb = PerfilturnoManager.getPerfilturnos(PerfilturnoManager.buildSearchCriteria(param));
	 simpleResponseService(response, AjaxUtils.buildAjaxULContentFromListObj(mgb.getAlmacen(),methodos, PerfilturnoHelper.COMPLEX_ID_GET_METHOD,"Perfilturno"));
 } 



 public void servicePerfilturnoElement(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
  StringBuffer cadena=null;
  Criteria c= new Criteria();
  int claveId=-1;
  claveId=WebUtils.getintParam(request, "perfilturno.IDTP");
  if (claveId!=-1)
  {
	  c.add(PerfilturnoPeer.IDTP, claveId);
  }
  c.addAscendingOrderByColumn(PerfilturnoPeer.IDTP);
  PerfilturnoGroupBean trgb = PerfilturnoManager.getPerfilturnos(c);
  
  if (trgb.getTotalSize()!=0)
  {
	  String [] parametros={
		PerfilturnoHelper.IDTP_GET_METHOD_NAME
		,PerfilturnoHelper.IDPERFIL_GET_METHOD_NAME+"PerfilturnoParsed"
		,PerfilturnoHelper.IDTURNO_GET_METHOD_NAME+"PerfilturnoParsed"
		,PerfilturnoHelper.VALORCOSTE_GET_METHOD_NAME+"PerfilturnoParsed"
	  };
	  cadena=trgb.buildXml(parametros,null,"ISO-8859-1");	
	  cadena.insert(cadena.indexOf("</result>"),getPathElementPerfilturno(request,response));  
  }
  xmlResponseService(response, cadena);
 } 
 

 protected StringBuffer updateIdtpResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(PerfilturnoManager.getPerfilturno(Integer.parseInt(a.get(0).toString())).getIdtpPerfilturnoParsed());
 }  
 

 protected StringBuffer updateIdperfilResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(PerfilturnoManager.getPerfilturno(Integer.parseInt(a.get(0).toString())).getIdperfilPerfilturnoParsed());
 }  
 

 protected StringBuffer updateIdturnoResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(PerfilturnoManager.getPerfilturno(Integer.parseInt(a.get(0).toString())).getIdturnoPerfilturnoParsed());
 }  
 

 protected StringBuffer updateValorcosteResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(PerfilturnoManager.getPerfilturno(Integer.parseInt(a.get(0).toString())).getValorcostePerfilturnoParsed());
 }  
 
 
 
 public void servicePerfilturnoPerfiles(HttpServletRequest request, HttpServletResponse response) throws IOException, TorqueException, ServletException
 {
  String cadena=null;
  Criteria c= new Criteria();
  int claveId=-1;
  claveId=WebUtils.getintParam(request, "perfiles.IDPERFIL");
  if (claveId!=-1)
  {
	  c.add(PerfilesPeer.IDPERFIL, claveId);
  }
  c.addAscendingOrderByColumn(PerfilesPeer.IDPERFIL);
  PerfilesGroupBean trgb = PerfilesManager.getPerfiless(c);
  
  if (trgb.getTotalSize()!=0)
  {
	  cadena = "<?xml version=\"1.0\" encoding=\"ISO-8859-1\" ?>";
	  cadena = cadena + "<result><perfilturno.IDPERFIL>" + trgb.getPerfiles(0).getULContentPerfilesParsed()  + "</perfilturno.IDPERFIL></result>";
  }
  
  xmlResponseService(response, new StringBuffer(cadena));
 }  
  			
 
 public void servicePerfilturnoTurnos(HttpServletRequest request, HttpServletResponse response) throws IOException, TorqueException, ServletException
 {
  String cadena=null;
  Criteria c= new Criteria();
  int claveId=-1;
  claveId=WebUtils.getintParam(request, "turnos.IDTURNO");
  if (claveId!=-1)
  {
	  c.add(TurnosPeer.IDTURNO, claveId);
  }
  c.addAscendingOrderByColumn(TurnosPeer.IDTURNO);
  TurnosGroupBean trgb = TurnosManager.getTurnoss(c);
  
  if (trgb.getTotalSize()!=0)
  {
	  cadena = "<?xml version=\"1.0\" encoding=\"ISO-8859-1\" ?>";
	  cadena = cadena + "<result><perfilturno.IDTURNO>" + trgb.getTurnos(0).getULContentTurnosParsed()  + "</perfilturno.IDTURNO></result>";
  }
  
  xmlResponseService(response, new StringBuffer(cadena));
 }  
  			

 public void serviceGetPerfilturnoDetallePdf(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
	 String[] getMethodos= new String[] {
		PerfilturnoHelper.IDTP_GET_METHOD_NAME
		,PerfilturnoHelper.IDPERFIL_GET_METHOD_NAME+"PerfilturnoParsed"
		,PerfilturnoHelper.IDTURNO_GET_METHOD_NAME+"PerfilturnoParsed"
		,PerfilturnoHelper.VALORCOSTE_GET_METHOD_NAME+"PerfilturnoParsed"
			 };
	  
	 
	 PerfilturnoGroupBean tgb = new PerfilturnoGroupBean();
	 try
	{
		tgb.setElemento(PerfilturnoHelper.getPerfilturno(request));
	} catch (TorqueException e)
	{
		logger.severe(e.getMessage());
	}
	
	 byte[] content =  PdfUtils.getBytes(replaceStringBuffer(tgb.buildXml(getMethodos, null,"ISO-8859-1"),"n/a"," "), perfilturno_transformer,"ISO-8859-1");
	 response.addHeader("content-disposition","attachment;filename=Perfilturno.pdf");
	 response.setContentType("application/pdf");
	 response.setHeader("Cache-Control", "");//para que funcione en IE
	 response.setContentLength(content.length);
	 response.getOutputStream().write(content);
	 response.getOutputStream().flush();  
	 response.getOutputStream().close();
	
 }  

 public void servicePerfilturnoTableContentPdf(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
  	utf8RequestService(request);
  	Criteria c= new Criteria();
  	String paramQuery =  WebUtils.getStringParam(request, "query");
  	if ((paramQuery != null)&& (paramQuery.compareTo("")!=0) )
		c = PerfilturnoManager.buildSearchCriteria(paramQuery);   
  	c =criteriaPerfilturnoTableContent(request,c);	  
  	PerfilturnoGroupBean tgb = PerfilturnoManager.getPerfilturnos(c);
  
  	String[] methodos= new String[] {	
		PerfilturnoHelper.IDPERFIL_GET_METHOD_NAME+"PerfilturnoParsed"
		,PerfilturnoHelper.IDTURNO_GET_METHOD_NAME+"PerfilturnoParsed"
		,PerfilturnoHelper.VALORCOSTE_GET_METHOD_NAME+"PerfilturnoParsed"
			};
  
	 byte[] content =  PdfUtils.getBytes(replaceStringBuffer(tgb.buildXml(methodos, null,"ISO-8859-1"),"n/a"," "), perfilturnos_transformer,"ISO-8859-1");
	 response.addHeader("content-disposition","attachment;filename=ListaPerfilturno.pdf");
	 response.setContentType("application/pdf");
	 response.setHeader("Cache-Control", "");//para que funcione en IE
	 response.setContentLength(content.length);
	 response.getOutputStream().write(content);
	 response.getOutputStream().flush();  
	 response.getOutputStream().close();
 }

}


