package net.idtoki.adimde.controller;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.ResourceBundle;
import java.util.logging.Logger;

import javax.servlet.ServletConfig;
import javax.servlet.ServletContext;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.xml.transform.Source;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.stream.StreamSource;

import org.apache.torque.TorqueException;
import org.apache.torque.util.Criteria;

import net.idtoki.adimde.manager.TipotrabajosManager;
import net.idtoki.adimde.group.TipotrabajosGroupBean;
import net.idtoki.adimde.helper.TipotrabajosHelper;
import net.idtoki.adimde.model.TipotrabajosPeer;
import net.idtoki.adimde.model.Tipotrabajos;


import net.idtoki.adimde.helper.ProduccionesHelper;


import net.zylk.tools.ajax.AjaxUtils;
import net.zylk.tools.ajax.AjaxUtils.DinamicGridBean;
import net.zylk.tools.format.FormatUtils;
import net.zylk.tools.pdf.PdfUtils;
import net.zylk.tools.xml.XmlUtils;
import net.zylk.torque.TorqueUtils;
import net.zylk.web.WebUtils;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Oct 02 10:34:00 CEST 2006]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
 
 
public class TipotrabajosController
    extends net.idtoki.adimde.controller.BaseTipotrabajosController
{
 private static final Logger logger = Logger.getLogger("net.idtoki.adimde.controller.TipotrabajosController");
 private TransformerFactory tFactory = TransformerFactory.newInstance();
 private Transformer tipotrabajos_transformer = null;  
 private Transformer tipotrabajoss_transformer = null; 

 public void init(ServletConfig config)
 {
	super.init();
	ResourceBundle resource = ResourceBundle.getBundle("net/idtoki/adimde/app/config/app-config");
	File tipotrabajos = new File(resource.getString("app.xsl.templates.dir")+"/PdfTipotrabajos.xslt");
	Source xslSource = new StreamSource(tipotrabajos);
	File tipotrabajoss = new File(resource.getString("app.xsl.templates.dir")+"/PdfListaTipotrabajos.xslt");
	Source xslSourceT = new StreamSource(tipotrabajoss); 	  
	try{
		tipotrabajos_transformer = tFactory.newTransformer(xslSource);
		tipotrabajoss_transformer = tFactory.newTransformer(xslSourceT);			  
	}catch (Exception e){
	  e.printStackTrace();
	}
 }


//Función para la inserción/actualización de registros

public void serviceAddTipotrabajos(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 //Con esto se consigue transformar el request a UTF
	 //para temas de acentos y otros caracteres
	 utf8RequestService(request);

	 //recojo los parametros del formulario y doy de alta un nuevo elmento
	 try
	 {
		 Tipotrabajos elTipotrabajos = TipotrabajosHelper.createObj(request);
		 TipotrabajosGroupBean gbTipotrabajos = new TipotrabajosGroupBean();
		 gbTipotrabajos.setElemento(elTipotrabajos);
		 gbTipotrabajos.save();
	 }
	 catch(TorqueException te)
	 {
		 response.sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
	 }
 }


//Función para la eliminación de un registro
//este método invoca al método public void deleteTipotrabajos(int idBorrar)
//definido en el TipotrabajosManager
 public void serviceDeleteTipotrabajos(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 int idBorrar=-1;
	 idBorrar=WebUtils.getintParam(request, "borrarId");
	 if (idBorrar!=-1)
 		 if (TipotrabajosManager.borraTipotrabajos(idBorrar))
			 WebUtils.writeXmlResponse(response,XmlUtils.buildXmlOKResponse("ISO-8859-1"));
		 else
			 WebUtils.writeXmlResponse(response,XmlUtils.buildXmlNotOKResponse("ISO-8859-1"));			 
 }


// Funciones para las ordenaciones y filtrados de información

 private Criteria ordenacion(Criteria c,String CampoOrdenacion,String OrdenOrdenacion) 
 { 
 	if((OrdenOrdenacion != null )&& (OrdenOrdenacion.compareTo("ASC")==0))
 		if ((CampoOrdenacion != null))
 		{
 			c.addAscendingOrderByColumn(CampoOrdenacion.toString());
 		}
 	if  ((OrdenOrdenacion != null) && (OrdenOrdenacion.compareTo("DESC")==0))
 		if ((CampoOrdenacion != null))
		{
 			c.addDescendingOrderByColumn(CampoOrdenacion.toString());
 		}
 	return c;
 }

private Criteria filtro(Criteria c,int filtro) 
{ 
	String cadena = null;
	 switch (filtro)
	 {
	 case 1:
		  //Caso uno de Filtrado
		  //c.add(Campo,valor);
		  break;
	 case 2:
		  //Caso dos de Filtrado
		  //c.add(Campo,valor);
		  break;
	 default:
		 //caso por defecto
		 break;
	 }
	return c;
}

 public StringBuffer replaceStringBuffer (StringBuffer strBA, String strOrigen, String strDestino) 
 {
	 return new StringBuffer(strBA.toString().replaceAll(strOrigen,strDestino));
 }

 private Criteria criteriaTipotrabajosTableContent(HttpServletRequest request,Criteria c) throws IOException, ServletException
 {
 	String param = "";	 
	  String paramSortCol =  WebUtils.getStringParam(request, "sort_col");
	  String paramSortDir =  WebUtils.getStringParam(request, "sort_dir");
	  int paramFiltro =  WebUtils.getintParam(request, "filtro");
	  c = ordenacion(c,paramSortCol,paramSortDir);
	  c = filtro(c,paramFiltro);

 	  return c;
 } 
 
 public String getPathElementTipotrabajos(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
	 Criteria c= new Criteria();
	 String strPath = "";
	 int claveId=-1;
	 int claveFkId=-1;	 
	 claveId=WebUtils.getintParam(request, "tipotrabajos.IDTIPOTRABAJO");
	 if (claveId!=-1)
	 {
		c.add(TipotrabajosPeer.IDTIPOTRABAJO, claveId);
		TipotrabajosGroupBean trgb = TipotrabajosManager.getTipotrabajoss(c);							
		strPath = trgb.getTipotrabajos(0).getPathTipotrabajosParsed(request.getQueryString());
	 }
	 return "<path>" + strPath + "</path>";
 } 
 
 public String getPathTableContentTipotrabajos(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
	 Criteria c= new Criteria();
	 String strPath = "";
	 int claveId=-1;	 
	 return "<path>" + strPath + "</path>";
 }  


public void  serviceTipotrabajosTableContent(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
	 utf8RequestService(request);
	 int numElemPedidosBD = 40;
	 int gap = 0;//gap = viewedRows - numElemVisiblesUltPag	  
	 DinamicGridBean dgb = WebUtils.getDinamicGridBeanParam(request,numElemPedidosBD,gap); 
	 Criteria c =TipotrabajosManager.buildSearchCriteria(dgb);
	 c =criteriaTipotrabajosTableContent(request,c);	 
	 TipotrabajosGroupBean cgb = TipotrabajosManager.getTipotrabajoss(c);
	 dgb.setTotalSize(cgb.getTotalSize());
	  
	 String[] methodos= new String[] {
		TipotrabajosHelper.NOMBRE_GET_METHOD_NAME+"TipotrabajosParsed"
		,TipotrabajosHelper.DESCRIPCION_GET_METHOD_NAME+"TipotrabajosParsed"
		,TipotrabajosHelper.COSTE_GET_METHOD_NAME+"TipotrabajosParsed"
		,"getHijosProduccionesTipotrabajos"
		,"getEditTipotrabajos"
		,"getDeleteTipotrabajos"
	};
	 
	 StringBuffer cadena=null;
	 cadena = AjaxUtils.buildXmlAjaxResponseTableContentFromListObj(cgb.getAlmacen(),methodos,TipotrabajosHelper.IDTIPOTRABAJO_GET_METHOD_NAME, dgb,"ISO-8859-1"); 
	 cadena.insert(cadena.indexOf("</ajax-response>"),"<response type='object' id='divPath'>" + getPathTableContentTipotrabajos(request,response) + "</response>");
	 xmlResponseService(response,cadena); 
 }  

 public void serviceTipotrabajosUlContent(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
	 String[] methodos= new String[] {
	 		"getULContentTipotrabajosParsed"
			 };
	 String param =  WebUtils.getStringParam(request, "value");
	 if(param==null || param.length() <= 0)
		 param =  WebUtils.getStringParam(request, new ProduccionesHelper().getIdtipotrabajoName());
	 	 
	 TipotrabajosGroupBean mgb = TipotrabajosManager.getTipotrabajoss(TipotrabajosManager.buildSearchCriteria(param));
	 simpleResponseService(response, AjaxUtils.buildAjaxULContentFromListObj(mgb.getAlmacen(),methodos, TipotrabajosHelper.COMPLEX_ID_GET_METHOD,"Tipotrabajos"));
 } 



 public void serviceTipotrabajosElement(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
  StringBuffer cadena=null;
  Criteria c= new Criteria();
  int claveId=-1;
  claveId=WebUtils.getintParam(request, "tipotrabajos.IDTIPOTRABAJO");
  if (claveId!=-1)
  {
	  c.add(TipotrabajosPeer.IDTIPOTRABAJO, claveId);
  }
  c.addAscendingOrderByColumn(TipotrabajosPeer.IDTIPOTRABAJO);
  TipotrabajosGroupBean trgb = TipotrabajosManager.getTipotrabajoss(c);
  
  if (trgb.getTotalSize()!=0)
  {
	  String [] parametros={
		TipotrabajosHelper.IDTIPOTRABAJO_GET_METHOD_NAME
		,TipotrabajosHelper.NOMBRE_GET_METHOD_NAME+"TipotrabajosParsed"
		,TipotrabajosHelper.DESCRIPCION_GET_METHOD_NAME+"TipotrabajosParsed"
		,TipotrabajosHelper.COSTE_GET_METHOD_NAME+"TipotrabajosParsed"
	  };
	  cadena=trgb.buildXml(parametros,null,"ISO-8859-1");	
	  cadena.insert(cadena.indexOf("</result>"),getPathElementTipotrabajos(request,response));  
  }
  xmlResponseService(response, cadena);
 } 
 

 protected StringBuffer updateIdtipotrabajoResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(TipotrabajosManager.getTipotrabajos(Integer.parseInt(a.get(0).toString())).getIdtipotrabajoTipotrabajosParsed());
 }  
 

 protected StringBuffer updateNombreResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(TipotrabajosManager.getTipotrabajos(Integer.parseInt(a.get(0).toString())).getNombreTipotrabajosParsed());
 }  
 

 protected StringBuffer updateDescripcionResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(TipotrabajosManager.getTipotrabajos(Integer.parseInt(a.get(0).toString())).getDescripcionTipotrabajosParsed());
 }  
 

 protected StringBuffer updateCosteResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(TipotrabajosManager.getTipotrabajos(Integer.parseInt(a.get(0).toString())).getCosteTipotrabajosParsed());
 }  
 
 

 public void serviceGetTipotrabajosDetallePdf(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
	 String[] getMethodos= new String[] {
		TipotrabajosHelper.IDTIPOTRABAJO_GET_METHOD_NAME
		,TipotrabajosHelper.NOMBRE_GET_METHOD_NAME+"TipotrabajosParsed"
		,TipotrabajosHelper.DESCRIPCION_GET_METHOD_NAME+"TipotrabajosParsed"
		,TipotrabajosHelper.COSTE_GET_METHOD_NAME+"TipotrabajosParsed"
			 };
	  
	 
	 TipotrabajosGroupBean tgb = new TipotrabajosGroupBean();
	 try
	{
		tgb.setElemento(TipotrabajosHelper.getTipotrabajos(request));
	} catch (TorqueException e)
	{
		logger.severe(e.getMessage());
	}
	
	 byte[] content =  PdfUtils.getBytes(replaceStringBuffer(tgb.buildXml(getMethodos, null,"ISO-8859-1"),"n/a"," "), tipotrabajos_transformer,"ISO-8859-1");
	 response.addHeader("content-disposition","attachment;filename=Tipotrabajos.pdf");
	 response.setContentType("application/pdf");
	 response.setHeader("Cache-Control", "");//para que funcione en IE
	 response.setContentLength(content.length);
	 response.getOutputStream().write(content);
	 response.getOutputStream().flush();  
	 response.getOutputStream().close();
	
 }  

 public void serviceTipotrabajosTableContentPdf(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
  	utf8RequestService(request);
  	Criteria c= new Criteria();
  	String paramQuery =  WebUtils.getStringParam(request, "query");
  	if ((paramQuery != null)&& (paramQuery.compareTo("")!=0) )
		c = TipotrabajosManager.buildSearchCriteria(paramQuery);   
  	c =criteriaTipotrabajosTableContent(request,c);	  
  	TipotrabajosGroupBean tgb = TipotrabajosManager.getTipotrabajoss(c);
  
  	String[] methodos= new String[] {	
		TipotrabajosHelper.NOMBRE_GET_METHOD_NAME+"TipotrabajosParsed"
		,TipotrabajosHelper.DESCRIPCION_GET_METHOD_NAME+"TipotrabajosParsed"
		,TipotrabajosHelper.COSTE_GET_METHOD_NAME+"TipotrabajosParsed"
			};
  
	 byte[] content =  PdfUtils.getBytes(replaceStringBuffer(tgb.buildXml(methodos, null,"ISO-8859-1"),"n/a"," "), tipotrabajoss_transformer,"ISO-8859-1");
	 response.addHeader("content-disposition","attachment;filename=ListaTipotrabajos.pdf");
	 response.setContentType("application/pdf");
	 response.setHeader("Cache-Control", "");//para que funcione en IE
	 response.setContentLength(content.length);
	 response.getOutputStream().write(content);
	 response.getOutputStream().flush();  
	 response.getOutputStream().close();
 }

}


